<div class="column column-wide">
  <div class="widget">
    <h1 class="post-title">Laporan Sertifikat</h1>
    <div class="divider">&nbsp;</div>

    <div class="report-content">
        <div class="report-col">
            <div class="report-time">
                <h3>April 2016</h3>
            </div>
            <ol>
              <li>Nama Peserta Sertifikat Memasang Radio <a href="#">Download</a> </li>
            </ul>
        </div>
        <div class="report-col">
            <div class="report-time">
                <h3>Maret 2016</h3>
            </div>
            <ol>
              <li>Nama Peserta Sertifikat Perbaikan Mobil <a href="#">Download</a> </li>
            </ul>
        </div>
    </div>

  </div>
  <div class="cleaner">&nbsp;</div>
</div>
