<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Laporan Pelatihan
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="custom-heading">
              <h2>Laporan Pelatihan P2KGK di Tahun 2016</h2>
          </div><!-- .custom-heading end -->
          <div class="table-responsive">
            <table class="events-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Laporan</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <td>1.</td>
                      <td>April 2016</td>
                      <td>Nama Peserta Pelatihan Memasang Radio</td>
                      <td><a href="#">Download</a></td>
                    </tr>
                    <tr>
                      <td>2.</td>
                      <td>April 2016</td>
                      <td>Nama Peserta Pelatihan Memasang Radio</td>
                      <td><a href="#">Download</a></td>
                    </tr>
                    <tr>
                      <td>3.</td>
                      <td>April 2016</td>
                      <td>Nama Peserta Pelatihan Memasang Radio</td>
                      <td><a href="#">Download</a></td>
                    </tr>
                    <tr>
                      <td>4.</td>
                      <td>April 2016</td>
                      <td>Nama Peserta Pelatihan Memasang Radio</td>
                      <td><a href="#">Download</a></td>
                    </tr>
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>
