<?php
	$session_editor=new Zend_Session_Namespace('session_admin');
		  $role = $session_editor->roles;
			//Zend_Debug::dump($session_editor->user_id);die();

?>
<html>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"></script>
<script type="text/javascript">

	$(function() {
		$("table").tablesorter({debug: true})
		$("a.append").click(appendData);


	});

</script>
	<body>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
		<div class="panel panel-info">
		<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i>&nbsp;<b>LIST PELATIHAN</b>

		</div>
		<table class="table">
		        <thead>
		          <tr align="center">
		          	<th width="100">No</th>
		            <th>Nama Pelatihan</th>
		            <th>Tanggal Pelatihan</th>
		            <th colspan="2">Action</th>
		          </tr>
		        </thead>
		        <tbody>
		         <?php for($a=0;$a < count($this->detail);$a++){
		         	$b = $a+1;
		         		?>
		         <tr>
		         	<td><?php echo $b;?></td>
		         	<td>Ujian Bahasa indonesia<?php //echo $this->detail[$a]['judul'];?></td>
		         	<td><?php echo $this->detail[$a]['waktu'];?></td>
		         	<td width="50px"><a class="btn btn-default btn-lg active" href="#" style="cursor: pointer;"><span class="glyphicon glyphicon-edit">Edit</span></a></td>
		         	<td width="50px"> <a class="btn btn-default btn-lg active" style="cursor: pointer;" onclick="hps('<?php //echo $this->detail[$a]['id_berita']?>')"><span class="glyphicon glyphicon-remove-circle">Delete</span></a></td>
		         </tr>
		         <?php }?>
		        </tbody>
		        <tfoot>
		        </tfoot>
		      </table>

		      </form>
		</div>

		<script>

		function hps(id){
			$.post('<?php echo $this->baseUrl()."/admin/admin/delete/id"?>',{key: id}, function(data){
		          if(data.edit==true) {
					alert('Data Clear');
					parent.location.href = "<?php echo $this->baseUrl()?>/admin/admin/index";
			      } else {
			    	  alert('Failed Clear Data');
			      }
		      });

		}
		</script>
	</body>
</html>
