<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="custom-heading">
              <h2>Edit My Account</h2>
          </div><!-- .custom-heading end -->
          <form class="login-form wpcf7" action="#" method="post">
            <div class="row">
              <div class="col-md-12 custom-bkg bkg-dark-blue dark">
                <fieldset>
                  <label for="nis">NIS <span class="required">*</span></label>
                  <input type="text" name="nis" id="nis" value="" class="input-text wpcf7-text">
                </fieldset>
                <fieldset>
                  <label for="nama">Nama Lengkap <span class="required">*</span></label>
                  <input type="text" name="nama" id="nama" value="" class="input-text wpcf7-text">
                </fieldset>
                <fieldset>
                  <label for="jkelamin">Jenis Kelamin <span class="required">*</span></label>
                  <select name="jkelamin" class="input-text wpcf7-select" id="jkelamin">
                    <option value="">-- Pilih --</option>
                    <option value="L">Laki-laki</option>
                    <option value="P">Perempuan</option>
                   </select>
                </fieldset>
                <fieldset>
                  <label for="tlp">No Telepon/Handphone <span class="required">*</span></label>
                  <input type="text" name="tlp" id="tlp" value="" class="input-text wpcf7-text">
                </fieldset>
                <fieldset>
                  <label for="alamat">Alamat <span class="required">*</span></label>
                  <textarea name="alamat" rows="8" cols="40" class="input-text wpcf7-textarea"></textarea>
                </fieldset>
                <fieldset>
                  <label for="email">Email <span class="required">*</span></label>
                  <input type="text" name="email" id="email" value="" class="input-text wpcf7-text">
                </fieldset>
                <fieldset>
                  <label for="password">Password <span class="required">*</span></label>
                  <input type="password" name="password" id="password" value="" class="input-text wpcf7-text">
                </fieldset>
                <fieldset>
                  <label for="confirm">Confrim Password <span class="required">*</span></label>
                  <input type="password" name="confirm" id="confirm" value="" class="input-text wpcf7-text">
                </fieldset>
                <fieldset>
                  <label for="foto">Upload Foto <span class="required">*</span></label>
                  <input type="file" name="foto" id="foto" class="input-text">
                </fieldset>
                <fieldset>
                  <label for="kec">Kecamatan <span class="required">*</span></label>
                  <select name="kec" class="input-text wpcf7-select">
                    <option value="">-- Pilih Kecamatan --</option>
                    <option value="6408">Cakung</option>
                    <option value="6403">Cipayung</option>
                    <option value="6402">Ciracas</option>
                    <option value="6407">Duren Sawit</option>
                    <option value="6406">Jatinegara</option>
                    <option value="6405">Kramat Jati</option>
                    <option value="6404">Makasar</option>
                    <option value="6410">Matraman</option>
                    <option value="6401">Pasar Rebo</option>
                    <option value="6409">Pulo Gadung</option>
                  </select>
                </fieldset>
                <fieldset>
                  <label for="tingkat_sekolah">Tingkat Sekolah <span class="required">*</span></label>
                  <select name="tingkat_sekolah" class="input-text wpcf7-select" id="tingkat_sekolah">
                    <option value="">-- Pilih Tingkat Sekolah --</option>
                    <option value="">TK</option>
                    <option value="">SD</option>
                    <option value="">SMP</option>
                    <option value="">SMA</option>
                    <option value="">SMK</option>
                  </select>
                </fieldset>
                <fieldset>
                  <label for="nama_sekolah">Nama Sekolah <span class="required">*</span></label>
                  <select name="nama_sekolah" class="input-text wpcf7-select" id="nama_sekolah">
                    <option value="">-- Pilih Tingkat Sekolah Dahulu--</option>
                  </select>
                </fieldset>
                <input type="submit" class="wpcf7-submit" value="Edit" />
              </div>
            </div>
          </form>
        </div>
      </div>
  </div>
</div>
