<div class="column column-wide column-wide-parent column-last">
  <div class="widget">
    <h1 class="post-title">Nilai</h1>
    <div class="divider">&nbsp;</div>
    <div class="post-content">
      <table border="1">
        <tbody>
          <tr style="border: 1px solid #ccc; padding: 3px;">
            <th style="text-align: center;" align="center">No</th>
            <th style="text-align: center;" align="center">Program</th>
            <th style="text-align: center;" align="center">KKM</th>
            <th style="text-align: center;" align="center">Nilai</th>
            <th style="text-align: center;" align="center">Status</th>

          </tr>
          <tr style="border: 1px solid #ccc; padding: 3px;">
            <td>1.</td>
            <td>
              Pelatihan Asesor Kompetensi dan Lisensi Otomotif
            </td>
            <td>65</td>
            <td>80</td>
            <td>Lulus</td>
          </tr>
          <tr style="border: 1px solid #ccc; padding: 3px;">
            <td>2.</td>
            <td>
              Pelatihan Asesor Kompetensi dan Lisensi Akuntansi
            </td>
            <td>65</td>
            <td>80</td>
            <td>Lulus</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
