<div class="column column-wide column-wide-parent column-last">
  <div class="widget">
    <h1 class="post-title">Daftar Pelatihan </h1>
    <div class="divider">&nbsp;</div>
    <div class="post-content">
      <table border="1">
        <tbody>
          <tr style="border: 1px solid #ccc; padding: 3px;">
            <th style="text-align: center;" align="center">No</th>
            <th style="text-align: center;" align="center">Gelombang</th>
            <th style="text-align: center;" align="center">Tanggal</th>
            <th style="text-align: center;" align="center">Program</th>
            <th style="text-align: center;" align="center" width="125">Sasaran Peserta</th>
            <th style="text-align: center;" align="center">Status</th>
            <th style="text-align: center;" align="center">Opsi</th>

          </tr>
          <tr style="border: 1px solid #ccc; padding: 3px;">
            <td>1.</td>
            <td>Gelombang ke-1</td>
            <td>25/05/2016 s.d 29/05/2016</td>
            <td>
              Pelatihan Asesor Kompetensi dan Lisensi Otomotif
            </td>
            <td>Guru SMK</td>
            <td>Pendaftaran masih terbuka</td>
            <td> <a href="#">Daftar</a> </td>
          </tr>
          <tr style="border: 1px solid #ccc; padding: 3px;">
            <td>2.</td>
            <td>Gelombang ke-1</td>
            <td>25/05/2016 s.d 29/05/2016</td>
            <td>
              Pelatihan Asesor Kompetensi dan Lisensi Akuntansi
            </td>
            <td>Guru SMK</td>
            <td>Pendaftaran masih terbuka</td>
            <td> <a href="#">Daftar</a> </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
