<div class="column column-wide">
  <div class="widget">
    <h1 class="post-title">Berita</h1>
    <div class="divider">&nbsp;</div>
    <ul class="posts-archive archives-columns-one">
      <?php foreach ($this->data as $article) { ?>
      <li class="loop-post-single">
        <div class="post-cover">
          <a href="<?php echo $this->baseUrl();?>/article/detail/p/<?php echo $article['id_artikel']?>" title="<?php echo $article['judul'];?>">
            <img src="<?php echo $this->baseUrl();?>/img/Artikel/<?php echo $article['gambar'];?>" alt="<?php echo $article['judul'];?>" width="210" height="100">
          </a>
        </div>
        <div class="post-excerpt">
          <p class="post-meta">
            <time datetime="<?php echo $article['waktu'];?>" pubdate=""><?php echo $article['waktu'];?></time>
          </p>
        <h2>
          <a href="<?php echo $this->baseUrl();?>/article/detail/p/<?php echo $article['id_artikel']?>" title="<?php echo $article['judul'];?>"><?php echo $article['judul'];?></a>
        </h2>
        <p><?php echo $article['isi'];  ?></p>
      </div>
      <div class="cleaner">&nbsp;</div>
    </li>
    <li class="divider">&nbsp;</li>
    <?php } ?>

  </ul>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
