<?php
$model = new Application_Model_RegisterModel();
$kecamatan = $model->loadKecamatan();
// $mapel = $model->loadMapel();
// $sekolah = $model->loadSekolah();
// $jabatan = $model->loadJabatan();
$golongan = $model->loadGolongan();
$ruang = $model->loadRuang();
$statpeg = $model->loadStatpeg();
$ijazah = $model->loadIjazah();

?>
<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/register">Register</a>
              </li>
              <li>
                Pendaftaran Guru
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
  <div class="container">
    <div class="custom-heading">
        <h2>Pendaftaran Guru</h2>
        <?php
            if($this->message != '') {
              echo $this->message;
            }
        ?>
    </div><!-- .custom-heading end -->
    <form class="login-form wpcf7" action="" method="post">
      <div class="row">
        <div class="col-md-6 custom-bkg bkg-dark-blue dark">
          <h3>Register I</h3>
          <!-- <fieldset>
            <label for="jenis_sek">Jenis Sekolah <span class="required">*</span></label>
            <select name="jenis_sek" id="jenis_sek" class="input-text wpcf7-select">
              <option value="1">Reguler</option>
              <option value="2">Paket</option>
            </select>
          </fieldset> -->
          <fieldset>
            <label for="jenis_peg">Kelompok Pegawai <span class="required">*</span></label>
            <select name="jenis_peg" class="input-text wpcf7-select" required="required">
              <option value="1">Tenaga Pendidik</option>
              <option value="2">Tenaga Kependidikan</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="kec">Kecamatan <span class="required">*</span></label>
            <select name="kec" class="input-text wpcf7-select kecamatan" required="required">
              <option value="">-- Pilih Kecamatan --</option>
              <?php foreach ($kecamatan as $kec) {?>
              <option value="<?php echo $kec['id_kec'];?>">
                <?php echo $kec['nama_kec'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset id="tingkat">
            <label for="tingkat_sekolah">Tingkat Sekolah <span class="required">*</span></label>
            <select name="tingkat_sekolah" class="input-text wpcf7-select" id="tingkat_sekolah" required="required">
              <option value="">-- Pilih Tingkat Sekolah --</option>
              <option value="TK">TK</option>
              <option value="SD">SD</option>
              <option value="SMP">SMP</option>
              <option value="SMA">SMA</option>
              <option value="SMK">SMK</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="nama_sekolah">Nama Sekolah <span class="required">*</span></label>
            <select name="nama_sekolah" class="input-text wpcf7-select" id="nama_sekolah" required="required">
              <option value="">-- Pilih Tingkat Sekolah dan Kecamatan Dahulu--</option>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="umur">Umur (Harus Angka)<span class="required">*</span></label>
              <input type="text" name="umur" id="umur" value="" class="input-text wpcf7-text" required="required">
            </div>
            <div class="form-wide">
              <label for="masa_kerja">Masa Kerja (Harus Angka)<span class="required">*</span></label>
              <input type="text" name="masa_kerja" id="masa_kerja" value="" class="input-text wpcf7-text" required="required">
            </div>
          </fieldset>
          <fieldset>
            <label for="jkelamin">Jenis Kelamin <span class="required">*</span></label>
            <select name="jkelamin" class="input-text wpcf7-select" id="jkelamin" required="required">
              <option value="">-- Pilih --</option>
              <option value="L">Laki-laki</option>
              <option value="P">Perempuan</option>
             </select>
          </fieldset>
          <fieldset>
            <label for="mapel">Mata Pelajaran <span class="required">*</span></label>
            <select name="mapel" class="input-text wpcf7-select" id="mapel" required="required">
              <option value="">-- Pilih --</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="status">Status Sekolah <span class="required">*</span></label>
            <select name="status" class="input-text wpcf7-select" id="status" required="required">
              <option value="">-- Pilih --</option>
              <option value="1">Negeri</option>
              <option value="2">Swasta</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="stat_peg">Status Kepegawaian <span class="required">*</span></label>
            <select name="stat_peg" class="input-text wpcf7-select" id="stat_peg" required="required">
              <option value="">-- Pilih --</option>
              <?php foreach ($statpeg as $sp) {?>
              <option value="<?php echo $sp['id_statuspeg'];?>">
                <?php echo $sp['nama_statuspeg'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="gol_ruang">Golongan <span class="required">*</span></label>
              <select name="gol_ruang" class="input-text wpcf7-select" id="gol_ruang" required="required">
                <option value="">-- Pilih --</option>
                <?php foreach ($golongan as $gol) {?>
                <option value="<?php echo $gol['id_golongan'];?>">
                  <?php echo $gol['nama_golongan'];?>
                </option>
                <?php } ?>
              </select>
            </div>
            <div class="form-wide">
              <label for="ruang">Ruang <span class="required">*</span></label>
              <select name="ruang" class="input-text wpcf7-select" id="ruang" required="required">
                <option value="">-- Pilih --</option>
                <?php foreach ($ruang as $ru) {?>
                <option value="<?php echo $ru['id_ruang'];?>">
                  <?php echo $ru['nama_ruang'];?>
                </option>
                <?php } ?>
              </select>
            </div>
          </fieldset>
          <fieldset>
            <label for="jabatan">Jabatan <span class="required">*</span></label>
            <select name="jabatan" class="input-text wpcf7-select" id="jabatan" required="required">
              <option value="">-- Pilih Jabatan --</option>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="sertifikasi">Sertifikasi <span class="required">*</span></label>
              <select name="sertifikasi" class="input-text wpcf7-select" id="sertifikasi" required="required">
                <option value="">-- Pilih --</option>
                <option value="1">Ya</option>
                <option value="2">Tidak</option>
              </select>
             </div>
             <div class="form-wide">
               <label for="thn_sertifikasi">Tahun <span class="required">*</span></label>
               <input type="text" name="thn_sertifikasi" id="thn_sertifikasi" value="" class="input-text wpcf7-text">
             </div>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
                <label for="pendidikan">Ijazah Terakhir <span class="required">*</span></label>
                <select name="pendidikan" id="pendidikan" class="input-text wpcf7-select" required="required">
                  <option value="">-- Pilih --</option>
                  <?php foreach ($ijazah as $ij) {?>
                  <option value="<?php echo $ij['id_ijazah'];?>">
                    <?php echo $ij['nama_ijazah'];?>
                  </option>
                  <?php } ?>
                </select>
              </div>
              <div class="form-wide">
                <label for="thn_pendidikan">Tahun <span class="required">*</span></label>
                <input type="text" name="thn_pendidikan" id="thn_pendidikan" value="" class="input-text wpcf7-text" required="required">
              </div>
          </fieldset>
          <fieldset>
            <label for="domisili">Domisili Sekarang <span class="required">*</span></label>
            <select name="domisili" id="domisili" class="input-text wpcf7-select" required="required">
              <option value="">-- Pilih --</option>
              <option value="1">DKI Jakarta</option>
              <option value="2">Luar DKI Jakarta</option>
            </select>
          </fieldset>
        </div>

        <div class="col-md-6 custom-bkg bkg-dark-blue dark">
          <h3>Register II</h3>
          <fieldset>
            <label for="nip">NIP <span class="required">*</span></label>
            <input type="text" name="nip" id="nip" value="" class="input-text wpcf7-text" required="required">
          </fieldset>
          <fieldset>
            <label for="nama">Nama Lengkap <span class="required">*</span></label>
            <input type="text" name="nama" id="nama" value="" class="input-text wpcf7-text" required="required">
          </fieldset>
          <fieldset>
            <label for="tlp">No Telepon/Handphone <span class="required">*</span></label>
            <input type="text" name="tlp" id="tlp" value="" class="input-text wpcf7-text" required="required">
          </fieldset>
          <fieldset>
            <label for="alamat">Alamat <span class="required">*</span></label>
            <textarea name="alamat" rows="8" cols="40" class="input-text  wpcf7-textarea" required="required"></textarea>
          </fieldset>
          <fieldset>
            <label for="email">Email <span class="required">*</span></label>
            <input type="text" name="email" id="email" value="" class="input-text wpcf7-text" required="required">
            <div class="alert-email"></div>
          </fieldset>
          <fieldset>
            <label for="password">Password <span class="required">*</span></label>
            <input type="password" name="password" id="password" value="" class="input-text wpcf7-text" required="required">
          </fieldset>
          <fieldset>
            <label for="confirm">Confrim Password <span class="required">*</span></label>
            <input type="password" name="confirm" id="confirm" value="" class="input-text wpcf7-text" required="required">
            <div class="alert-con-pass"></div>
          </fieldset>
          <!-- <fieldset>
            <label for="foto">Upload Foto <span class="required">*</span></label>
            <input type="file" name="foto" id="foto" class="input-text">
          </fieldset> -->
          <fieldset>
            <div class="required">
                * Wajib Di isi!
            </div>
          </fieldset>
          <div class="alert alert-info">
            Harap mengecek kembali data yang di masukkan sebelum di submit!
          </div>
          <input id="submits" type="submit" class="wpcf7-submit" value="Daftar" />
        </div>

      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
  function isEmail(email) {
    var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    return regex.test(email);
  }
  $(document).ready(function() {
    $('#umur, #masa_kerja, #thn_sertifikasi, #thn_pendidikan, #nip, #tlp').bind('keypress', function (e) {
        return (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57) && e.which != 46) ? false : true;
    });

    $('#sertifikasi').change(function() {
        if($(this).val() == 2) {
          $("#thn_sertifikasi").prop("disabled", true);
          $("#thn_sertifikasi").removeAttr('required');
        } else {
          $("#thn_sertifikasi").prop("disabled", false);
          $("#thn_sertifikasi").focus();
          $("#thn_sertifikasi").attr('required','required');
        }
    });

    $('#email').focusout(function() {
      var value = $(this).val();
      var base_url = "<?php echo $this->baseUrl() ?>";
      if(!isEmail(value)){
        $(".alert-email").text("Email tidak valid!");
        $(".alert-email").show();
      } else {
        $(".alert-email").text("");
        $(".alert-email").hide();
        $.ajax({
            type: "POST",
            data: {
                'email' : value,
                'akses' : 'guru',
            },
            url: base_url+"/register/cekallemail",
            beforeSend: function(){
              $(".alert-email").text("Cek Ketersedian Email..");
            },
            success: function(data){
              if(data.data !="") {
                $(".alert-email").text(data.data);
                $(".alert-email").show();
              } else {
                $(".alert-email").hide();
              }
            }
        });
      }
    });

    $('#confirm').focusout(function () {
      var c = $(this).val();
      var p = $("#password").val();
      if(c!=p) {
        $(".alert-con-pass").text("Password tidak sama!");
        $(".alert-con-pass").show();
      } else {
        $(".alert-con-pass").hide();
        $(".alert-con-pass").text("");
      }
    });

    $('.kecamatan, #tingkat_sekolah').change(function() {
      var tingkat = $('#tingkat_sekolah').val();
      var kec = $('.kecamatan').val();
      var base_url = "<?php echo $this->baseUrl() ?>";
      if(tingkat != 0 && kec != 0) {
        $.ajax({
            type: "POST",
            data: {
                'id_kec' : kec,
                'tingkat' : tingkat,
            },
            url: base_url+"/register/ajaxsekolah",
            beforeSend: function(){
              $('#nama_sekolah').html("<option>Harap Tunggu...</option>");
            },
            success: function(data){
              var sekolah = '<option value="">-- Pilih Sekolah --</option>';
              for(j=0; j < data.data.length;j++){
                 sekolah+='<option value='+data.data[j]['induk_sekolah']+'>'+data.data[j]['nama_sekolah']+'</option>';
               }
               $('#nama_sekolah').html(sekolah);

            }
        });
      }

      $.ajax({
          type: "POST",
          data: {
              'tingkat' : tingkat,
          },
          url: base_url+"/register/ajaxmapel",
          beforeSend: function(){
            $('#mapel').html("<option>Harap Tunggu...</option>");
          },
          success: function(data){
            var mapel = '<option value="">-- Pilih --</option>';
            for(j=0; j < data.data.length;j++){
               mapel+='<option value='+data.data[j]['id_mapel']+'>'+data.data[j]['nama_mapel']+'</option>';
             }
             $('#mapel').html(mapel);

          }
      });

      $.ajax({
          type: "POST",
          data: {
              'tingkat' : tingkat,
          },
          url: base_url+"/register/ajaxjabatan",
          beforeSend: function(){
            $('#jabatan').html("<option>Harap Tunggu...</option>");
          },
          success: function(data){
            var jabatan = '<option value="">-- Pilih Jabatan --</option>';
            for(j=0; j < data.data.length;j++){
               jabatan+='<option value='+data.data[j]['id_jabatan']+'>'+data.data[j]['nama_jabatan']+'</option>';
             }
             $('#jabatan').html(jabatan);

          }
      });
    });
  });
</script>
