<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/register">Register</a>
              </li>
              <li>
                Pendaftaran Guru
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
  <div class="container">
    <div class="custom-heading">
        <h2>Pendaftaran Guru</h2>
    </div><!-- .custom-heading end -->
    <form class="login-form wpcf7" action="#" method="post">
      <div class="row">
        <div class="col-md-6 custom-bkg bkg-dark-blue dark">
          <h3>Register I</h3>
          <fieldset>
            <label for="jenis_sek">Jenis Sekolah <span class="required">*</span></label>
            <select name="jenis_sek" id="jenis_sek" class="input-text wpcf7-select">
              <option value="1">Reguler</option>
              <option value="3">Paket</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="jenis_peg">Kelompok Pegawai <span class="required">*</span></label>
            <select name="jenis_peg" class="input-text wpcf7-select">
              <option value="G">Tenaga Pendidik</option>
              <option value="P">Tenaga Kependidikan</option>
            </select>
          </fieldset>
          <!-- <fieldset>
            <label for="keyword">Kata Kunci</label>
            <div class="keyword-content" style="width:100%;display:inline-block;">
              <input type="text" name="keyword" value="" class="input-text wpcf7-text" style="width:45%; margin-right:10px;">
              <select name="berdasarkan" class="input-text wpcf7-select" style="width:45%;">
                <option value="">-- Pilih Kriteria --</option>
                <option value="nama">Nama</option>
                <option value="nip">NIP</option>
                <option value="nik">NIK</option>
                <option value="nip">NRK</option>
                <option value="nip">NIGB</option>
                <option value="nuptk">NUPTK</option>
              </select>
            </div>
          </fieldset> -->
          <fieldset>
            <label for="kec">Kecamatan <span class="required">*</span></label>
            <select name="kec" class="input-text wpcf7-select">
              <option value="">-- Pilih Kecamatan --</option>
              <option value="6408">Cakung</option>
              <option value="6403">Cipayung</option>
              <option value="6402">Ciracas</option>
              <option value="6407">Duren Sawit</option>
              <option value="6406">Jatinegara</option>
              <option value="6405">Kramat Jati</option>
              <option value="6404">Makasar</option>
              <option value="6410">Matraman</option>
              <option value="6401">Pasar Rebo</option>
              <option value="6409">Pulo Gadung</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="tingkat_sekolah">Tingkat Sekolah <span class="required">*</span></label>
            <select name="tingkat_sekolah" class="input-text wpcf7-select" id="tingkat_sekolah">
              <option value="">-- Pilih Tingkat Sekolah --</option>
              <option value="">TK</option>
              <option value="">SD</option>
              <option value="">SMP</option>
              <option value="">SMA</option>
              <option value="">SMK</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="nama_sekolah">Nama Sekolah <span class="required">*</span></label>
            <select name="nama_sekolah" class="input-text wpcf7-select" id="nama_sekolah">
              <option value="">-- Pilih Tingkat Sekolah Dahulu--</option>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="umur">Umur <span class="required">*</span></label>
              <input type="text" name="umur" id="umur" value="" class="input-text wpcf7-text">
            </div>
            <div class="form-wide">
              <label for="masa_kerja">Masa Kerja <span class="required">*</span></label>
              <input type="text" name="masa_kerja" id="masa_kerja" value="" class="input-text wpcf7-text">
            </div>
          </fieldset>
          <fieldset>
            <label for="jkelamin">Jenis Kelamin <span class="required">*</span></label>
            <select name="jkelamin" class="input-text wpcf7-select" id="jkelamin">
              <option value="">-- Pilih --</option>
              <option value="L">Laki-laki</option>
              <option value="P">Perempuan</option>
             </select>
          </fieldset>
          <fieldset>
            <label for="mapel">Mata Pelajaran <span class="required">*</span></label>
            <select name="mapel" class="input-text wpcf7-select" id="mapel">
              <option value="">-- Pilih --</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="status">Status Sekolah <span class="required">*</span></label>
            <select name="status" class="input-text wpcf7-select" id="status">
              <option value="">-- Pilih --</option>
              <option value="1">Negeri</option>
              <option value="2">Swasta</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="stat_peg">Status Kepegawaian <span class="required">*</span></label>
            <select name="stat_peg" class="input-text wpcf7-select" id="stat_peg">
              <option value="">-- Pilih --</option>
              <option value="G01">PNS</option>
              <option value="G00">CPNS</option>
              <option value="G04">Honor K-1 / PTT</option>
              <option value="G13">Honor K-2</option>
              <option value="G03">Honor Murni Negeri 2005+</option>
              <option value="G06">PHL (K-2)</option>
              <option value="G07">PHL (Honor Murni)</option>
              <option value="G05">Guru Bantu</option>
              <option value="G11">Guru DPK</option>
              <option value="G12">Guru Depag</option>
              <option value="G02">Guru Tetap Yayasan</option>
              <option value="G14">Guru Tidak Tetap Yayasan</option>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="gol_ruang">Golongan <span class="required">*</span></label>
              <select name="gol_ruang" class="input-text wpcf7-select" id="gol_ruang">
                <option value="">-- Pilih --</option>
                <option value="01">Gol I</option>
                <option value="02">Gol II</option>
                <option value="03">Gol III</option>
                <option value="04">Gol IV</option>
              </select>
            </div>
            <div class="form-wide">
              <label for="ruang">Ruang <span class="required">*</span></label>
              <select name="ruang" class="input-text wpcf7-select" id="ruang">
                <option value="">-- Pilih --</option>
                <option value="a">a</option>
                <option value="b">b</option>
                <option value="c">c</option>
                <option value="d">d</option>
                <option value="e">e</option>
              </select>
            </div>
          </fieldset>
          <fieldset>
            <label for="jabatan">Jabatan <span class="required">*</span></label>
            <select name="jabatan" class="input-text wpcf7-select" id="jabatan">
              <option value="">-- Pilih Jabatan --</option>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="sertifikasi">Sertifikasi <span class="required">*</span></label>
              <select name="sertifikasi" class="input-text wpcf7-select" id="sertifikasi">
                <option value="">-- Pilih --</option>
                <option value="1">Ya</option>
                <option value="0">Tidak</option>
              </select>
             </div>
             <div class="form-wide">
               <label for="thn_sertifikasi">Tahun <span class="required">*</span></label>
               <input type="text" name="thn_sertifikasi" id="thn_sertifikasi" value="" class="input-text wpcf7-text">
             </div>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
                <label for="pendidikan">Ijazah Terakhir <span class="required">*</span></label>
                <select name="pendidikan" id="pendidikan" class="input-text wpcf7-select">
                  <option value="">-- Pilih --</option>
                  <option value="S13">SLTA</option>
                  <option value="S21">PGSLP/D-1</option>
                  <option value="S22">PGSLA/D-2</option>
                  <option value="S23">Sarmud/D-3</option>
                  <option value="S31">Sarjana/S-1</option>
                  <option value="S32">Pasca Sarjana/S-2</option>
                  <option value="S33">Doktor/S-3</option>
                </select>
              </div>
              <div class="form-wide">
                <label for="thn_pendidikan">Tahun <span class="required">*</span></label>
                <input type="text" name="thn_pendidikan" id="thn_pendidikan" value="" class="input-text wpcf7-text">
              </div>
          </fieldset>
          <fieldset>
            <label for="domisili">Domisili Sekarang <span class="required">*</span></label>
            <select name="domisili" id="domisili" class="input-text wpcf7-select">
              <option value="">-- Pilih --</option>
              <option value="0">DKI Jakarta</option>
              <option value="1">Luar DKI Jakarta</option>
            </select>
          </fieldset>
        </div>

        <div class="col-md-6 custom-bkg bkg-dark-blue dark">
          <h3>Register II</h3>
          <fieldset>
            <label for="nip">NIP <span class="required">*</span></label>
            <input type="text" name="nip" id="nip" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="nama">Nama Lengkap <span class="required">*</span></label>
            <input type="text" name="nama" id="nama" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="tlp">No Telepon/Handphone <span class="required">*</span></label>
            <input type="text" name="tlp" id="tlp" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="alamat">Alamat <span class="required">*</span></label>
            <textarea name="alamat" rows="8" cols="40" class="input-text  wpcf7-textarea"></textarea>
          </fieldset>
          <fieldset>
            <label for="email">Email <span class="required">*</span></label>
            <input type="text" name="email" id="email" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="password">Password <span class="required">*</span></label>
            <input type="password" name="password" id="password" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="confirm">Confrim Password <span class="required">*</span></label>
            <input type="password" name="confirm" id="confirm" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="foto">Upload Foto <span class="required">*</span></label>
            <input type="file" name="foto" id="foto" class="input-text">
          </fieldset>
          <fieldset>
            <div class="required">
                * Wajib Di isi!
            </div>
          </fieldset>
          <input type="submit" class="wpcf7-submit" value="Daftar" />
        </div>

      </div>
    </form>
  </div>
</div>
