<?php
$model = new Application_Model_RegisterModel();
$kecamatan = $model->loadKecamatan();
$mapel = $model->loadMapel();
$sekolah = $model->loadSekolah();
$jabatan = $model->loadJabatan();
$golongan = $model->loadGolongan();
$ruang = $model->loadRuang();
$statpeg = $model->loadStatpeg();
$ijazah = $model->loadIjazah();

?>
<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/register">Register</a>
              </li>
              <li>
                Pendaftaran Guru
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
  <div class="container">
    <div class="custom-heading">
        <h2>Pendaftaran Guru</h2>
        <?php
            if($this->message != '') {
              echo $this->message;
            }
        ?>
    </div><!-- .custom-heading end -->
    <form class="login-form wpcf7" action="#" method="post">
      <div class="row">
        <div class="col-md-6 custom-bkg bkg-dark-blue dark">
          <h3>Register I</h3>
          <fieldset>
            <label for="jenis_sek">Jenis Sekolah <span class="required">*</span></label>
            <select name="jenis_sek" id="jenis_sek" class="input-text wpcf7-select">
              <option value="1">Reguler</option>
              <option value="3">Paket</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="jenis_peg">Kelompok Pegawai <span class="required">*</span></label>
            <select name="jenis_peg" class="input-text wpcf7-select">
              <option value="G">Tenaga Pendidik</option>
              <option value="P">Tenaga Kependidikan</option>
            </select>
          </fieldset>
          <!-- <fieldset>
            <label for="keyword">Kata Kunci</label>
            <div class="keyword-content" style="width:100%;display:inline-block;">
              <input type="text" name="keyword" value="" class="input-text wpcf7-text" style="width:45%; margin-right:10px;">
              <select name="berdasarkan" class="input-text wpcf7-select" style="width:45%;">
                <option value="">-- Pilih Kriteria --</option>
                <option value="nama">Nama</option>
                <option value="nip">NIP</option>
                <option value="nik">NIK</option>
                <option value="nip">NRK</option>
                <option value="nip">NIGB</option>
                <option value="nuptk">NUPTK</option>
              </select>
            </div>
          </fieldset> -->
          <fieldset>
            <label for="kec">Kecamatan <span class="required">*</span></label>
            <select name="kec" class="input-text wpcf7-select">
              <option value="">-- Pilih Kecamatan --</option>
              <?php foreach ($kecamatan as $kec) {?>
              <option value="<?php echo $kec['id_kec'];?>">
                <?php echo $kec['nama_kec'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset>
            <label for="tingkat_sekolah">Tingkat Sekolah <span class="required">*</span></label>
            <select name="tingkat_sekolah" class="input-text wpcf7-select" id="tingkat_sekolah">
              <option value="">-- Pilih Tingkat Sekolah --</option>
              <option value="">TK</option>
              <option value="">SD</option>
              <option value="">SMP</option>
              <option value="">SMA</option>
              <option value="">SMK</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="nama_sekolah">Nama Sekolah <span class="required">*</span></label>
            <select name="nama_sekolah" class="input-text wpcf7-select" id="nama_sekolah">
              <option value="">-- Pilih Tingkat Sekolah dan Kecamata Dahulu--</option>
              <?php foreach ($sekolah as $sklh) {?>
              <option value="<?php echo $sklh['induk_sekolah'];?>">
                <?php echo $sklh['nama_sekolah'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="umur">Umur <span class="required">*</span></label>
              <input type="text" name="umur" id="umur" value="" class="input-text wpcf7-text">
            </div>
            <div class="form-wide">
              <label for="masa_kerja">Masa Kerja <span class="required">*</span></label>
              <input type="text" name="masa_kerja" id="masa_kerja" value="" class="input-text wpcf7-text">
            </div>
          </fieldset>
          <fieldset>
            <label for="jkelamin">Jenis Kelamin <span class="required">*</span></label>
            <select name="jkelamin" class="input-text wpcf7-select" id="jkelamin">
              <option value="">-- Pilih --</option>
              <option value="L">Laki-laki</option>
              <option value="P">Perempuan</option>
             </select>
          </fieldset>
          <fieldset>
            <label for="mapel">Mata Pelajaran <span class="required">*</span></label>
            <select name="mapel" class="input-text wpcf7-select" id="mapel">
              <option value="">-- Pilih --</option>
              <?php foreach ($mapel as $mapels) {?>
              <option value="<?php echo $mapels['id_mapel'];?>">
                <?php echo $mapels['nama_mapel'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset>
            <label for="status">Status Sekolah <span class="required">*</span></label>
            <select name="status" class="input-text wpcf7-select" id="status">
              <option value="">-- Pilih --</option>
              <option value="1">Negeri</option>
              <option value="2">Swasta</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="stat_peg">Status Kepegawaian <span class="required">*</span></label>
            <select name="stat_peg" class="input-text wpcf7-select" id="stat_peg">
              <option value="">-- Pilih --</option>
              <?php foreach ($statpeg as $sp) {?>
              <option value="<?php echo $sp['id_statuspeg'];?>">
                <?php echo $sp['nama_statuspeg'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="gol_ruang">Golongan <span class="required">*</span></label>
              <select name="gol_ruang" class="input-text wpcf7-select" id="gol_ruang">
                <option value="">-- Pilih --</option>
                <?php foreach ($golongan as $gol) {?>
                <option value="<?php echo $gol['id_golongan'];?>">
                  <?php echo $gol['nama_golongan'];?>
                </option>
                <?php } ?>
              </select>
            </div>
            <div class="form-wide">
              <label for="ruang">Ruang <span class="required">*</span></label>
              <select name="ruang" class="input-text wpcf7-select" id="ruang">
                <option value="">-- Pilih --</option>
                <?php foreach ($ruang as $ru) {?>
                <option value="<?php echo $ru['id_ruang'];?>">
                  <?php echo $ru['nama_ruang'];?>
                </option>
                <?php } ?>
              </select>
            </div>
          </fieldset>
          <fieldset>
            <label for="jabatan">Jabatan <span class="required">*</span></label>
            <select name="jabatan" class="input-text wpcf7-select" id="jabatan">
              <option value="">-- Pilih Jabatan --</option>
              <?php foreach ($jabatan as $jab) {?>
              <option value="<?php echo $jab['id_jabatan'];?>">
                <?php echo $jab['nama_jabatan'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
              <label for="sertifikasi">Sertifikasi <span class="required">*</span></label>
              <select name="sertifikasi" class="input-text wpcf7-select" id="sertifikasi">
                <option value="">-- Pilih --</option>
                <option value="1">Ya</option>
                <option value="0">Tidak</option>
              </select>
             </div>
             <div class="form-wide">
               <label for="thn_sertifikasi">Tahun <span class="required">*</span></label>
               <input type="text" name="thn_sertifikasi" id="thn_sertifikasi" value="" class="input-text wpcf7-text">
             </div>
          </fieldset>
          <fieldset>
            <div class="form-wide" style="margin-right:10px;">
                <label for="pendidikan">Ijazah Terakhir <span class="required">*</span></label>
                <select name="pendidikan" id="pendidikan" class="input-text wpcf7-select">
                  <option value="">-- Pilih --</option>
                  <?php foreach ($ijazah as $ij) {?>
                  <option value="<?php echo $ij['id_ijazah'];?>">
                    <?php echo $ij['nama_ijazah'];?>
                  </option>
                  <?php } ?>
                </select>
              </div>
              <div class="form-wide">
                <label for="thn_pendidikan">Tahun <span class="required">*</span></label>
                <input type="text" name="thn_pendidikan" id="thn_pendidikan" value="" class="input-text wpcf7-text">
              </div>
          </fieldset>
          <fieldset>
            <label for="domisili">Domisili Sekarang <span class="required">*</span></label>
            <select name="domisili" id="domisili" class="input-text wpcf7-select">
              <option value="">-- Pilih --</option>
              <option value="0">DKI Jakarta</option>
              <option value="1">Luar DKI Jakarta</option>
            </select>
          </fieldset>
        </div>

        <div class="col-md-6 custom-bkg bkg-dark-blue dark">
          <h3>Register II</h3>
          <fieldset>
            <label for="nip">NIP <span class="required">*</span></label>
            <input type="text" name="nip" id="nip" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="nama">Nama Lengkap <span class="required">*</span></label>
            <input type="text" name="nama" id="nama" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="tlp">No Telepon/Handphone <span class="required">*</span></label>
            <input type="text" name="tlp" id="tlp" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="alamat">Alamat <span class="required">*</span></label>
            <textarea name="alamat" rows="8" cols="40" class="input-text  wpcf7-textarea"></textarea>
          </fieldset>
          <fieldset>
            <label for="email">Email <span class="required">*</span></label>
            <input type="text" name="email" id="email" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="password">Password <span class="required">*</span></label>
            <input type="password" name="password" id="password" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="confirm">Confrim Password <span class="required">*</span></label>
            <input type="password" name="confirm" id="confirm" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="foto">Upload Foto <span class="required">*</span></label>
            <input type="file" name="foto" id="foto" class="input-text">
          </fieldset>
          <fieldset>
            <div class="required">
                * Wajib Di isi!
            </div>
          </fieldset>
          <input type="submit" class="wpcf7-submit" value="Daftar" />
        </div>

      </div>
    </form>
  </div>
</div>
