<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Register
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>

<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="custom-heading02">
                    <h2>Register</h2>
                    <p></p>
                </div>
            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->

        <div class="row p2kgkregister">
            <div class="col-md-6 col-sm-4">
                <div class="service-feature-box">
                    <div class="service-media">
                        <img src="<?php echo $this->baseUrl() ?>/img/gururegister.jpg" alt="Pendaftaran Guru"/>

                        <a href="<?php echo $this->baseUrl();?>/register/guru/" class="read-more02">
                            <span>
                                Daftar
                                <i class="fa fa-chevron-right"></i>
                            </span>
                        </a>
                    </div><!-- .service-media end -->

                    <div class="service-body">
                      <a href="<?php echo $this->baseUrl();?>/register/siswa/">
                        <div class="custom-heading">
                            <h4>Pendaftaran Guru</h4>
                        </div><!-- .custom-heading end -->
                      </a>
                      <p>We have a wide experience in overland industry specific logistic solutions like pharmaceutical logistics, retail and automotive logistics by train or road.
                      </p>

                    </div><!-- .service-body end -->
                </div><!-- .service-feature-box-end -->
            </div><!-- .col-md-4 end -->

            <div class="col-md-6 col-sm-4">
                <div class="service-feature-box">
                    <div class="service-media">
                        <img src="<?php echo $this->baseUrl() ?>/img/muridregister.jpg" alt="Pendaftaran Murid"/>

                        <a href="<?php echo $this->baseUrl();?>/register/siswa/" class="read-more02">
                            <span>
                                Daftar
                                <i class="fa fa-chevron-right"></i>
                            </span>
                        </a>
                    </div><!-- .service-media end -->

                    <div class="service-body">
                        <a href="<?php echo $this->baseUrl();?>/register/siswa/">
                          <div class="custom-heading">
                              <h4>Pendaftaran Siswa</h4>
                          </div><!-- .custom-heading end -->
                        </a>
                        <p>We have a wide experience in overland industry specific logistic solutions like pharmaceutical logistics, retail and automotive logistics by train or road.</p>

                    </div><!-- .service-body end -->
                </div><!-- .service-feature-box-end -->
            </div><!-- .col-md-4 end -->

        </div><!-- .row end -->
    </div><!-- .container end -->
</div><!-- .page-content end -->
