<div class="column column-wide">
  <div class="widget">
    <h1>Registrasi Siswa</h1>
  </div>
  <form class="login-form register" action="#" method="post">
    <div class="widget" style="display:inline-block;">
      <div class="step-content">
        <h2>Register</h2>
            <fieldset>
              <div class="input-form">
                  <label for="nis">NIS <em>*</em></label>
                  <input type="text" name="nis" id="nis" value="" class="input-text">
              </div>
              <div class="input-form">
                  <label for="nama">Nama Lengkap <em>*</em></label>
                  <input type="text" name="nama" id="nama" value="" class="input-text">
              </div>
              <div class="input-form">
                  <label for="jkelamin">Jenis Kelamin <em>*</em></label>
                  <select name="jkelamin" class="input-text" id="jkelamin">
                    <option value="">-- Pilih --</option>
                    <option value="L">Laki-laki</option>
                    <option value="P">Perempuan</option>
                   </select>
              </div>
              <div class="input-form">
                  <label for="tlp">No Telepon/Handphone <em>*</em></label>
                  <input type="text" name="tlp" id="tlp" value="" class="input-text">
              </div>
              <div class="input-form">
                  <label for="alamat">Alamat <em>*</em></label>
                  <textarea name="alamat" rows="8" cols="40" class="input-text"></textarea>
              </div>
              <div class="input-form">
                  <label for="email">Email <em>*</em></label>
                  <input type="text" name="email" id="email" value="" class="input-text">
              </div>
              <div class="input-form">
                  <label for="password">Password <em>*</em></label>
                  <input type="password" name="password" id="password" value="" class="input-text">
              </div>
              <div class="input-form">
                  <label for="confirm">Confrim Password <em>*</em></label>
                  <input type="password" name="confirm" id="confirm" value="" class="input-text">
              </div>
              <div class="input-form">
                  <label for="foto">Upload Foto <em>*</em></label>
                  <input type="file" name="foto" id="foto" class="input-text">
              </div>
              <div class="input-form">
                  <label for="kec">Kecamatan <em>*</em></label>
                  <select name="kec" class="input-text">
                    <option value="">-- Pilih Kecamatan --</option>
                    <option value="6408">Cakung</option>
                    <option value="6403">Cipayung</option>
                    <option value="6402">Ciracas</option>
                    <option value="6407">Duren Sawit</option>
                    <option value="6406">Jatinegara</option>
                    <option value="6405">Kramat Jati</option>
                    <option value="6404">Makasar</option>
                    <option value="6410">Matraman</option>
                    <option value="6401">Pasar Rebo</option>
                    <option value="6409">Pulo Gadung</option>
                  </select>
              </div>
              <div class="input-form">
                  <label for="tingkat_sekolah">Tingkat Sekolah <em>*</em></label>
                  <select name="tingkat_sekolah" class="input-text" id="tingkat_sekolah">
                    <option value="">-- Pilih Tingkat Sekolah --</option>
                    <option value="">TK</option>
                    <option value="">SD</option>
                    <option value="">SMP</option>
                    <option value="">SMA</option>
                    <option value="">SMK</option>
                  </select>
              </div>
              <div class="input-form">
                  <label for="nama_sekolah">Nama Sekolah <em>*</em></label>
                  <select name="nama_sekolah" class="input-text" id="nama_sekolah">
                    <option value="">-- Pilih Tingkat Sekolah Dahulu--</option>
                  </select>
              </div>
              <div class="input-form">
                  <div class="required">
                      * Wajib Di isi!
                  </div>
              </div>
              <div class="button-set">
                  <input type="submit" name="submit" value="Register" class="button gold">
              </div>
          </fieldset>
      </div>
    </div>
  </form>
  <div class="cleaner">&nbsp;</div>
</div>
