<?php
$model = new Application_Model_RegisterModel();
$kecamatan = $model->loadKecamatan();
?>
<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/register">Register</a>
              </li>
              <li>
                Pendaftaran Siswa
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
  <div class="container">
    <div class="custom-heading">
        <h2>Pendaftaran Siswa</h2>
    </div><!-- .custom-heading end -->
    <form class="login-form wpcf7" action="#" method="post">
      <div class="row">
        <div class="col-md-6 custom-bkg bkg-dark-blue dark">
          <fieldset>
            <label for="nis">NIS <span class="required">*</span></label>
            <input type="text" name="nis" id="nis" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="nama">Nama Lengkap <span class="required">*</span></label>
            <input type="text" name="nama" id="nama" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="jkelamin">Jenis Kelamin <span class="required">*</span></label>
            <select name="jkelamin" class="input-text wpcf7-select" id="jkelamin">
              <option value="">-- Pilih --</option>
              <option value="L">Laki-laki</option>
              <option value="P">Perempuan</option>
             </select>
          </fieldset>
          <fieldset>
            <label for="tlp">No Telepon/Handphone <span class="required">*</span></label>
            <input type="text" name="tlp" id="tlp" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="alamat">Alamat <span class="required">*</span></label>
            <textarea name="alamat" rows="8" cols="40" class="input-text wpcf7-textarea"></textarea>
          </fieldset>
          <fieldset>
            <label for="email">Email <span class="required">*</span></label>
            <input type="text" name="email" id="email" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="password">Password <span class="required">*</span></label>
            <input type="password" name="password" id="password" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="confirm">Confrim Password <span class="required">*</span></label>
            <input type="password" name="confirm" id="confirm" value="" class="input-text wpcf7-text">
          </fieldset>
          <fieldset>
            <label for="foto">Upload Foto <span class="required">*</span></label>
            <input type="file" name="foto" id="foto" class="input-text">
          </fieldset>
          <fieldset>
            <label for="kec">Kecamatan <span class="required">*</span></label>
            <select name="kec" class="input-text wpcf7-select kecamatan">
              <option value="">-- Pilih Kecamatan --</option>
              <?php foreach ($kecamatan as $kec) {?>
              <option value="<?php echo $kec['id_kec'];?>">
                <?php echo $kec['nama_kec'];?>
              </option>
              <?php } ?>
            </select>
          </fieldset>
          <fieldset>
            <label for="tingkat_sekolah">Tingkat Sekolah <span class="required">*</span></label>
            <select name="tingkat_sekolah" class="input-text wpcf7-select" id="tingkat_sekolah">
              <option value="0">-- Pilih Tingkat Sekolah --</option>
              <option value="TK">TK</option>
              <option value="SD">SD</option>
              <option value="SMP">SMP</option>
              <option value="SMA">SMA</option>
              <option value="SMK">SMK</option>
            </select>
          </fieldset>
          <fieldset>
            <label for="nama_sekolah">Nama Sekolah <span class="required">*</span></label>
            <select name="nama_sekolah" class="input-text wpcf7-select" id="nama_sekolah">
              <option value="">-- Pilih Tingkat Sekolah Dahulu--</option>
            </select>
          </fieldset>
          <fieldset>
            <div class="required">
                * Wajib Di isi!
            </div>
          </fieldset>
          <input type="submit" class="wpcf7-submit" value="Daftar" />
        </div>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.kecamatan, #tingkat_sekolah').change(function() {
      var tingkat = $('#tingkat_sekolah').val();
      var kec = $('.kecamatan').val();
      var base_url = "<?php echo $this->baseUrl() ?>";
      $.ajax({
          type: "POST",
          data: {
              'id_kec' : kec,
              'tingkat' : tingkat,
          },
          url: base_url+"/register/ajaxsekolah",
          success: function(data){
            var b = '';
            for(j=0; j < data.data.length;j++){
               b+='<option value='+data.data[j]['induk_sekolah']+'>'+data.data[j]['nama_sekolah']+'</option>';
             }
             $('#nama_sekolah').html(b);

          }
      });
    });
  });
</script>
