<div class="column column-wide column-wide-parent column-last">
  <div id="featured-posts" class="flexslider">
  <ul class="slides wpzoom-featured-posts">
    <li class="wpzoom-featured-post">
      <div class="post-cover">
        <a href="#" title="BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015">
          <img src="images/sikunir_edit_2_featured-715x300.jpg" alt="BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015" class="Thumbnail thumbnail homepage-slider " width="715" height="300">
        </a>
      </div>
      <div class="post-excerpt">
        <h2>
          <a href="#" title="Permalink to BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015">BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015</a>
        </h2>
        <p>BPPTIK menerima piagam penghargaan sebagai unit kerja terbaik ke-2 atas capaian kinerja realisasi anggaran pada Tahun Anggaran 2015 di lingkungan Badan Penelitian dan Pengembangan Sumber Daya Manusia (Balitbang SDM) Kementerian Komunikasi dan Informatika.</p>
      </div>
    </li>
    <li class="wpzoom-featured-post">
      <div class="post-cover">
        <a href="#" title="BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015">
          <img src="images/sikunir_edit_2_featured-715x300.jpg" alt="BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015" class="Thumbnail thumbnail homepage-slider " width="715" height="300">
        </a>
      </div>
      <div class="post-excerpt">
        <h2>
          <a href="#" title="Permalink to BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015">BPPTIK Terima Penghargaan Peringkat ke-2 Capaian Realisasi Anggaran Tahun Anggaran 2015</a>
        </h2>
        <p>BPPTIK menerima piagam penghargaan sebagai unit kerja terbaik ke-2 atas capaian kinerja realisasi anggaran pada Tahun Anggaran 2015 di lingkungan Badan Penelitian dan Pengembangan Sumber Daya Manusia (Balitbang SDM) Kementerian Komunikasi dan Informatika.</p>
      </div>
    </li>
  </ul>
  </div>
  <!-- nampilin berita sama article -->
  <?php
    $modelberita = new Application_Model_DbTables_NewsModel();
    $berita = $modelberita->getAllnewslimit();
    $modelartikel = new Application_Model_DbTables_ArtikelModel();
    $artikel = $modelartikel->getAllartikellimit();

  ?>

  <div class="cleaner">&nbsp;</div>
  <div class="column column-wide column-wide-child">
    <div class="widget wpzoom">
      Berita
      <?php foreach ($berita as $news ) {?>
        <b><?php echo $news['judul'];?></b>
      <?php }?>
    </div>

    <div class="widget wpzoom">
      Artikel
      <?php foreach ($artikel as $art ) {?>
        <b><?php echo $art['judul'];?></b>
      <?php }?>
    </div>
    <div class="cleaner">&nbsp;</div>

  </div>


  <div class="column column-narrow column-narrow-child column-last">

    <?php include("../application/views/scripts/include/sidebarhomepage.phtml"); ?>


    <div class="cleaner">&nbsp;</div>
  </div>
</div>
<div class="cleaner">&nbsp;</div>
