<div id="masterslider" class="master-slider ms-skin-default mb-0">
    <!-- first slide -->
    <div class="ms-slide">
        <!-- slide background -->
        <img src="masterslider/blank.gif" data-src="<?php echo $this->baseUrl();?>/images/kegiatan/2.jpg" alt="Strongest distribution network"/>

        <img class="ms-layer" src="masterslider/blank.gif" data-src="img/slider/slider-line.jpg" alt=""
             style="left: 30px; top: 310px;"
             data-type="image"
             data-effect="left(short)"
             data-duration="300"
             data-hide-effect="fade"
             data-delay="0"
             />
        <h2 class="ms-layer pi-caption01"
            style="left: 30px; top: 340px; font-size:30px"
            data-type="text"
            data-effect="left(short)"
            data-duration="300"
            data-hide-effect="fade"
            data-delay="300"
            >
            Pelatihan komputer
        </h2>
        <p class="ms-layer pi-text"
           style="left: 375px; top: 470px; font-size:25px"
           data-type="text"
           data-effect="top(short)"
           data-duration="300"
           data-hide-effect="fade"
           data-delay="600"
           >
            Pelatihan Guru SMK se jakarta timur di kantor P2KGK
        </p>
    </div><!-- .ms-slide end -->

    <div class="ms-slide">
        <!-- slide background -->
        <img src="masterslider/blank.gif" data-src="<?php echo $this->baseUrl();?>/images/kegiatan/1.jpg" alt="Strongest distribution network"/>

        <img class="ms-layer" src="masterslider/blank.gif" data-src="img/slider/slider-line.jpg" alt=""
             style="left: 30px; top: 310px;"
             data-type="image"
             data-effect="left(short)"
             data-duration="300"
             data-hide-effect="fade"
             data-delay="0"
             />
        <h2 class="ms-layer pi-caption01"
            style="left: 30px; top: 340px; font-size:30px"
            data-type="text"
            data-effect="left(short)"
            data-duration="300"
            data-hide-effect="fade"
            data-delay="300"
            >
            Pengenalan Mesin Industri
        </h2>
        <p class="ms-layer pi-text"
           style="left: 375px; top: 470px; font-size:25px"
           data-type="text"
           data-effect="top(short)"
           data-duration="300"
           data-hide-effect="fade"
           data-delay="600"
           >
          Pelatihan Guru SMK se jakarta timur di kantor P2KGK
        </p>
    </div><!-- .ms-slide end -->

</div><!-- #masterslider end -->

<!-- <div class="clear"></div> -->

<!-- content -->
<div class="page-content parallax parallax01 dark mb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="custom-heading02">
                    <h2 style="padding-bottom:20px;">Selamat datang di halaman resmi website P2KGK Jakarta Timur</h2>
                </div><!-- .custom-heading02 end -->
            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->

        <div class="row mb-30">
            <div class="col-md-6">
                <div class="service-icon-left">
                    <div class="icon-container triggerAnimation animated" data-animate="zoomIn">
                        <img src="img/svg/pi-checklist-2.svg" alt="checklist icon">
                    </div><!-- .icon-container end -->

                    <div class="service-details">
                        <h3>Daftar Pelatihan Online</h3>

                        <p>
                            Info pendaftaran penerimaaan peserta guru dan siswa di P2KGK JAKTIM.
                        </p>
                    </div><!-- .service-details end -->
                </div><!-- .service-icon-left end -->
            </div><!-- .col-md-6 end -->

            <div class="col-md-6">
                <div class="service-icon-left">
                    <div class="icon-container triggerAnimation animated" data-animate="zoomIn">
                        <img src="img/svg/pi-employees.svg" alt="globe icon">
                    </div><!-- .icon-container end -->

                    <div class="service-details">
                        <h3>Pelatihan Guru, Kejuruan dan Siswa</h3>

                        <p>
                            Nama pelatihan guru, kejuruan siswa yang akan dilakasanakan dan nama para peserta yang telah lulus seleksi adminitrasi
                        </p>
                    </div><!-- .service-details end -->
                </div><!-- .service-icon-left end -->
            </div><!-- .col-md-6 end -->
        </div><!-- .row.mb-30 end -->

        <div class="row">
            <div class="col-md-6">
                <div class="service-icon-left">
                    <div class="icon-container triggerAnimation animated" data-animate="zoomIn">
                        <img src="img/svg/pi-office.svg" alt="forklift truck icon">
                    </div><!-- .icon-container end -->

                    <div class="service-details">
                        <h3>Fasilitas Sarana dan Prasarana Memadai</h3>

                        <p>
                          Fasilitas yang menunjang para peserta didik guru dan siswa dalam melaksanakan pelatihan dan ujian
                        </p>
                    </div><!-- .service-details end -->
                </div><!-- .service-icon-left end -->
            </div><!-- .col-md-6 end -->

            <div class="col-md-6">
                <div class="service-icon-left">
                    <div class="icon-container triggerAnimation animated" data-animate="zoomIn">
                        <img src="img/svg/pi-online-test.svg" alt="touch icon">
                    </div><!-- .icon-container end -->

                    <div class="service-details">
                        <h3>Hasil Ujian Sertifikasi online</h3>

                        <p>
                            Dalam pelatihan siswa,kejuruan dan siswa yang telah melakasanakan ujian, dapat melihat hasil secara online.
                        </p>
                    </div><!-- .service-details end -->
                </div><!-- .service-icon-left end -->
            </div><!-- .col-md-6 end -->
        </div><!-- .row end -->
    </div><!-- .container end -->
</div><!-- .page-content end -->

<div class="page-content p2kgkinfo">
    <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-12">
            <div class="custom-heading">
                <h3>P2KGK New Training</h3>
                <span>
                  <a class="invert" href="<?php echo $this->baseUrl();?>/service/training/" rel="nofollow">view more</a>
                </span>
            </div><!-- .custom-heading end -->
            <div class="table-responsive">
                <table class="events-table">
                    <thead>
                        <tr>
                            <th>tanggal</th>
                            <th>nama pelatihan</th>
                            <th>peserta</th>
                            <th>jenis pelatihan</th>
                            <th>status</th>
                        </tr>
                    </thead>
                    <tbody>
            <?php
              $modelpel = new Application_Model_DbTables_PelatihanModel();
              $pelat = $modelpel->getAllpellimit();

              foreach ($pelat as $pelats ) {?>
                        <tr style="border-bottom: 1px solid #e6e6e6;">
                            <td class="event-date p2kgkdate">
                              <?php echo $pelats['tgl']?>
                            </td>
                            <td>
                                <?php echo $pelats['nama_pelatihan']?>
                            </td>
                            <td>
                              <?php echo $pelats['tingkat_peserta']?>
                            </td>
                            <td>
                              <?php
                                if($pelats['jenis_pelatihan']==1) {
                                  echo "Pelatihan";
                                } elseif($pelats['jenis_pelatihan']==2) {
                                  echo "Sertifikasi";
                                } else {
                                  echo "Pelatihan & Sertifikasi";
                                }
                              ?>
                            </td>
                            <td>
                              <?php
                              if($pelats['status_pendaftaran']==1) {
                                echo "Pendaftaran masih buka";
                              } else {
                                echo "<span style='color:#f00;'>Pendaftaran sudah tutup</span>";
                              }
                              ?>
                            </td>
                        </tr>
                        <?php } ?>

                    </tbody>
                </table><!-- .events-table end -->
              </div>
          </div>
          <div class="col-md-4 col-sm-12 custom-bkg bkg-dark-blue dark">
            <div class="custom-heading">
                <h3 style="width:100%;">P2KGK Jaktim</h3>
            </div><!-- .custom-heading end -->
            <div class="row">
            <div class="col-md-6 col-sm-4">
                <div class="team-member">
                    <img src="<?php echo $this->baseUrl();?>/img/Pimpinan/endang.jpg" alt="">
                    <div class="team-details">
                        <h5>Hj. dr Endang Wahyu Sinar Matahari. MM</h5>
                        <p class="position">
                            Kepala P2kGK
                        </p>
                    </div><!-- .team-details end -->
                </div><!-- .member end -->
            </div><!-- .col-md-4 end -->

            <div class="col-md-6 col-sm-4">
                <div class="team-member">
                    <img src="<?php echo $this->baseUrl();?>/img/Pimpinan/Suraji.jpg" alt="">
                    <div class="team-details">
                        <h5>Suraji</h5>
                        <p class="position">
                            Kepala Sub Bag TU
                        </p>
                    </div><!-- .team-details end -->
                </div><!-- .member end -->
            </div><!-- .col-md-4 end -->
          </div>
        </div>
    </div>
</div>

<!-- content -->
<div class="page-content p2kgkinfo">
    <div class="container">
        <div class="row">
          <?php
            $modelberita = new Application_Model_DbTables_NewsModel();
            $berita = $modelberita->getAllnewslimit();
            $modelartikel = new Application_Model_DbTables_ArtikelModel();
            $artikel = $modelartikel->getAllartikellimit();
            $modelagenda = new Application_Model_DbTables_AgendaModel();
            $agenda = $modelagenda->getAllagendalimit();
          ?>
            <div class="col-md-4 col-sm-6">
                <div class="custom-heading">
                    <h3>P2KGK News</h3>
                    <span>
                      <a class="invert" href="<?php echo $this->baseUrl();?>/news/" rel="nofollow">view more posts</a>
                    </span>
                </div><!-- .custom-heading end -->
                <ul class="pi-latest-posts clearfix">
                  <?php foreach ($berita as $news ) {?>
                    <li>
                      <div class="post-media">
                          <img src="<?php echo $this->baseUrl();?>/img/News/<?php echo $news['gambar'];?>" alt="<?php echo $news['judul'];?>"/>
                      </div><!-- .post-media end -->

                      <div class="post-details">
                          <div class="post-date">
                              <p>
                                  <i class="fa fa-calendar"></i>
                                  <?php echo $news['waktu'];?>
                              </p>
                          </div>

                          <a href="<?php echo $this->baseUrl();?>/news/detail/p/<?php echo $news['id_berita']?>">
                              <h4>
                                  <?php echo $news['judul'];?>
                              </h4>
                          </a>

                          <a href="<?php echo $this->baseUrl();?>/news/detail/p/<?php echo $news['id_berita']?>" class="read-more">
                              <span>
                                  Read more
                                  <i class="fa fa-chevron-right"></i>
                              </span>
                          </a>
                      </div><!-- .post-details end -->
                    </li>
                  <?php }?>
                </ul><!-- .pi-latest-posts end -->
            </div><!-- .col-md-4 end -->

            <div class="col-md-4 col-sm-6">
                <div class="custom-heading">
                    <h3>P2KGK Article</h3>
                      <span>
                        <a class="invert" href="<?php echo $this->baseUrl();?>/article/" rel="nofollow">view more posts</a>
                      </span>
                </div><!-- .custom-heading end -->
                <ul class="pi-latest-posts clearfix">
                  <?php foreach ($artikel as $art ) {?>
                    <li>
                      <div class="post-media">
                          <img src="<?php echo $this->baseUrl();?>/img/Artikel/<?php echo $art['gambar'];?>" alt="<?php echo $art['judul'];?>"/>
                      </div><!-- .post-media end -->

                      <div class="post-details">
                          <div class="post-date">
                              <p>
                                  <i class="fa fa-calendar"></i>
                                <?php echo $art['waktu'];?>
                              </p>
                          </div>

                          <a href="<?php echo $this->baseUrl();?>/article/detail/p/<?php echo $art['id_artikel']?>">
                              <h4>
                                  <?php echo $art['judul'];?>
                              </h4>
                          </a>

                          <a href="<?php echo $this->baseUrl();?>/article/detail/p/<?php echo $art['id_artikel']?>" class="read-more">
                              <span>
                                  Read more
                                  <i class="fa fa-chevron-right"></i>
                              </span>
                          </a>
                      </div><!-- .post-details end -->
                    </li>
                    <?php }?>

                </ul><!-- .pi-latest-posts end -->
            </div><!-- .col-md-4 end -->

            <div class="col-md-4 col-sm-6">
                <div class="custom-heading">
                    <h3>P2KGK Agenda</h3>
                    <span>
                      <a class="invert" href="<?php echo $this->baseUrl();?>/agenda/" rel="nofollow">view more posts</a>
                    </span>
                </div><!-- .custom-heading end -->
                <ul class="pi-latest-posts clearfix">
                  <?php foreach ($agenda as $age ) {?>

                    <li>
                      <div class="post-media">
                          <img src="<?php echo $this->baseUrl();?>/img/nivo-events@2x.png" alt="<?php echo $age['nama_agenda'];?>" style="width:auto; margin:0 auto;"/>
                      </div><!-- .post-media end -->
                      <div class="post-details">
                          <div class="post-date">
                              <p>
                                  <i class="fa fa-calendar"></i>
                                  <?php echo $age['tgl']?>
                              </p>
                          </div>

                          <a href="<?php echo $this->baseUrl();?>/agenda/detail/p/<?php echo $age['id_agenda']?>">
                              <h4>
                                  <?php echo $age['nama_agenda']?>
                              </h4>
                          </a>

                          <a href="<?php echo $this->baseUrl();?>/agenda/detail/p/<?php echo $age['id_agenda']?>" class="read-more">
                              <span>
                                  Read more
                                  <i class="fa fa-chevron-right"></i>
                              </span>
                          </a>
                      </div><!-- .post-details end -->
                    </li>
                    <?php } ?>
                </ul><!-- .pi-latest-posts end -->
            </div><!-- .col-md-4 end -->

        </div><!-- .row end -->
    </div><!-- .container end -->
</div><!-- .page-content end -->

<div class="page-content custom-bkg bkg-dark-blue dark p2kgkinfo">
  <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-6">
            <div class="custom-heading">
                <h3>P2KGK Facebook</h3>
            </div><!-- .custom-heading end -->
            <div class="fb-page" data-href="https://www.facebook.com/P2KGK-Jakarta-Timur-204466053220728" data-width="390" data-height="291" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>
            <div id="fb-root"></div>
            <script>(function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=126278130727907";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="custom-heading">
                <h3>P2KGK Google+</h3>
            </div><!-- .custom-heading end -->
            <!-- Tempatkan tag ini di head atau tepat sebelum tag body penutup. -->
            <script src="https://apis.google.com/js/platform.js" async defer>
              {lang: 'id'}
            </script>

            <!-- Tempatkan tag ini di mana pun Anda ingin widget ditampilkan. -->
            <div class="g-person" data-href="https://plus.google.com/110983658397925793542" data-theme="dark" data-rel="author"></div>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="custom-heading">
                <h3>P2KGK Twitter</h3>
            </div><!-- .custom-heading end -->
            <a class="twitter-timeline" href="https://twitter.com/p2kgkjaktim" data-widget-id="724216557786660864">Tweets by @p2kgkjaktim</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
      </div>
    </div>
</div><!-- .page-content end -->

<!-- end content -->
