<div class="column column-wide">
  <div class="widget">
    <!-- isi detail berita -->
    <h1 class="post-title">Sekretaris Badang Litbang SDM Kominfo Membuka Diklat CIO, ToT, dan Desain Grafis</h1>
    <p class="post-meta">
      By <a href="#" title="Pos-pos oleh Luhur Pidekso Arif" rel="author">Luhur Pidekso Arif</a> / <time datetime="2016-04-11" pubdate="">11 April 2016</time></p>
      <div class="divider">&nbsp;</div>
      <div class="post-content">

      <img class="aligncenter wp-image-1941 size-full" src="#">
      <p>isi berita</p>
    </div>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
