<div class="column column-wide">
  <div class="widget">
    <!-- isi detail berita -->
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
<div class="share-content">
  <span class='st_facebook_large' displayText='Facebook'></span>
  <span class='st_twitter_large' displayText='Tweet'></span>
  <span class='st__large' displayText=''></span>
  <span class='st_googleplus_large' displayText='Google +'></span>
  <span class='st_pinterest_large' displayText='Pinterest'></span>
  <span class='st_email_large' displayText='Email'></span>
</div>
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "0e28c62c-904d-4df1-bd19-5a90a01cf6eb", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
