<div class="column column-wide">
  <div class="widget">
    <!-- isi detail berita -->
    <h1 class="post-title"><?php echo $this->data[0]['judul']?></h1>
    <p class="post-meta">
      By Admin / <time datetime="<?php echo $this->data[0]['waktu']?>" pubdate=""><?php echo $this->data[0]['waktu']?></time></p>
      <div class="divider">&nbsp;</div>
      <div class="post-content">

      <img class="aligncenter wp-image-1941 size-full" src="<?php echo $this->baseUrl();?>/img/News/<?php echo $this->data[0]['gambar'];?>" alt="<?php echo $this->data[0]['judul'];?>">
      <p><?php echo $this->data[0]['isi'];?></p>
      <div class="divider">&nbsp;</div>
      <div class="share-news">
        <div class="share-text">
            Share :
        </div>
        <span class='st_facebook_large' displayText='Facebook'></span>
        <span class='st_twitter_large' displayText='Tweet'></span>
        <span class='st_googleplus_large' displayText='Google +'></span>
        <span class='st__large' displayText=''></span>
        <span class='st_pinterest_large' displayText='Pinterest'></span>
        <span class='st_email_large' displayText='Email'></span>
        <script type="text/javascript">var switchTo5x=true;</script>
        <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
        <script type="text/javascript">stLight.options({publisher: "0e28c62c-904d-4df1-bd19-5a90a01cf6eb", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
      </div>
    </div>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
