<div class="column column-wide">
  <div class="widget">
    <h1 class="post-title">Berita</h1>
    <div class="divider">&nbsp;</div>
    <ul class="posts-archive archives-columns-one">
      <li class="loop-post-single">
        <div class="post-cover">
          <a href="http://bpptik.kominfo.go.id/2016/03/02/1921/kembali-dibuka-kesempatan-diklat-teknis-bidang-tik-untuk-pns-pusat-dan-daerah/" title="Kembali Dibuka Kesempatan Diklat Teknis bidang TIK untuk PNS Pusat dan Daerah">
            <img src="http://bpptik.kominfo.go.id/wp-content/uploads/2016/03/20160302-diklat-tik-210x100.jpg" alt="Ilustrasi - Diklat Teknis bidang TIK di BPPTIK. (ist)" class="Thumbnail thumbnail loop-main " width="210" height="100">
          </a>
        </div>
        <div class="post-excerpt">
          <p class="post-meta">
          <time datetime="2016-03-02" pubdate="">2 Maret 2016</time> / <span class="category"><a href="http://bpptik.kominfo.go.id/category/berita/" rel="category tag">Berita</a></span>
        </p>
        <h2>
          <a href="http://bpptik.kominfo.go.id/2016/03/02/1921/kembali-dibuka-kesempatan-diklat-teknis-bidang-tik-untuk-pns-pusat-dan-daerah/" title="Kembali Dibuka Kesempatan Diklat Teknis bidang TIK untuk PNS Pusat dan Daerah">Kembali Dibuka Kesempatan Diklat Teknis bidang TIK untuk PNS Pusat dan Daerah</a>
        </h2>
        <p>Pada tahun anggaran 2016 ini kembali dibuka kesempatan Pendidikan dan Pelatihan (Diklat) Teknis bidang Teknologi Informasi dan Komunikasi (TIK) untuk para Pegawai Negeri Sipil (PNS) pusat dan daerah di seluruh Indonesia.</p>
      </div>
      <div class="cleaner">&nbsp;</div>
    </li>
    <li class="divider">&nbsp;</li>
  </ul>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
