<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="custom-heading">
              <h2>Daftar Pelatihan dan Sertifikasi</h2>
          </div><!-- .custom-heading end -->
          <div class="table-responsive">
              <table class="events-table">
                  <thead>
                      <tr>
                          <th>No</th>
                          <th>Tanggal</th>
                          <th>Gelombang</th>
                          <th>Program</th>
                          <th>Status</th>
                          <th>Opsi</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr style="border-bottom: 1px solid #e6e6e6;">
                          <td>1.</td>
                          <td class="event-date p2kgkdate">
                              25/05/2016 s.d 29/05/2016
                          </td>
                          <td>Gelombang 1</td>
                          <td>
                              <ol>
                                <li>Pelatihan Junior Network Administration dan Sertifikasi Junior Network Administrator</li>
                                <li>Pelatihan Junior Programmer dan Sertifikasi Junior Programmer</li>
                              </ol>
                          </td>
                          <td>
                              Pendaftaran masih buka
                          </td>
                          <td>
                              <a href="#">Daftar</a>
                          </td>
                      </tr>

                      <tr style="border-bottom: 1px solid #e6e6e6;">
                          <td>2.</td>
                          <td class="event-date p2kgkdate">
                              25/05/2016 s.d 29/05/2016
                          </td>
                          <td>Gelombang 1</td>
                          <td>
                              <ol>
                                <li>Pelatihan Junior Network Administration dan Sertifikasi Junior Network Administrator</li>
                                <li>Pelatihan Junior Programmer dan Sertifikasi Junior Programmer</li>
                              </ol>
                          </td>
                          <td>
                              Pendaftaran masih buka
                          </td>
                          <td>
                              <a href="#">Daftar</a>
                          </td>
                      </tr>
                  </tbody>
              </table><!-- .events-table end -->
            </div>
        </div>
      </div>
  </div>
</div>
