<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="custom-heading">
              <h2>Daftar Pelatihan dan Sertifikasi</h2>
          </div><!-- .custom-heading end -->
          <div class="table-responsive">
              <table class="events-table">
                  <thead>
                      <tr>
                          <th>No</th>
                          <th>Tanggal</th>
                          <th>Gelombang</th>
                          <th>Program</th>
                          <th>Status</th>
                          <th>Opsi</th>
                      </tr>
                  </thead>
                  <?php $a=0;?>
                  <tbody>
                      <?php foreach ($this->data as $data) {
                    $b = $a+1;
                    ?>

                      <tr style="border-bottom: 1px solid #e6e6e6;">
                          <td><?php echo $b;?></td>
                          <td class="event-date p2kgkdate">
                             <?php echo $data['tgl'];?>
                          </td>
                          <td>Gelombang <?php echo $data['gelombang'];?></td>
                          <td>
                              <?php echo $data['nama_pelatihan'];?>
                          </td>
                          <td>
                              <?php
                                if($data['status_pendaftaran']==1){
                                  echo 'Pendaftaran Masih Di Buka';
                                } else {
                                  echo 'Pendaftaran Tutup';
                                }
                              ?>
                          </td>
                          <?php if ($data['status_pendaftaran']==1) {?>
                          <td>
                              <a href="#">Daftar</a>
                              <span class="separator">|</span>
                              <a href="<?php echo $this->baseUrl();?>/user/3e72758f0fc77cdad787f58b41e9985f/detail/p/<?php echo $data['id_pelatihan'];?>"> Detail</a>
                          </td>
                          <?php } else { ?>
                            <td>
                              <a href="#"> Detail</a>
                            </td>
                          <?php }?>
                      </tr>
                  <?php
                    $a++;
                      } ?>
                  </tbody>
              </table><!-- .events-table end -->
            </div>
        </div>
      </div>
  </div>
</div>
