<style media="screen">
  .col-md-5 {padding: 0;}
  .table-responsive .table tbody td {
    text-align: left;
  }
  .job-end-date {float: right!important;}
</style>
<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="custom-heading">
              <h2>Daftar Pelatihan dan Sertifikasi</h2>
          </div><!-- .custom-heading end -->

          <div class="accordion careers">
            <?php $a=0;
            foreach ($this->data as $data) {
              $b = $a+1;

              ?>
              <div class="title ">
                <a href='#' class="clearfix">
                    <span class='job-position'><?php echo $data['nama_pelatihan'];?></span>
                    <span class='job-end-date'>
                      <i class="fa fa-calendar"></i>
                      <?php echo $data['tgl'];?></span>
                </a>
              </div><!-- .title end -->

              <div class="content clearfix">
                  <h4>Program</h4>
                  <p>
                      <?php echo $data['deskripsi'];?>
                  </p>
                  <br />

                  <div class="col-md-5">
                    <div class="table-responsive">
                      <table class="table">
                        <thead></thead>
                        <tbody>
                          <tr>
                            <td>Gelombang</td>
                            <td><?php echo $data['gelombang'];?></td>
                          </tr>
                          <tr>
                            <td>Jenis Pelatihan</td>
                            <?php
                              if($data['jenis_pelatihan']==1) {
                                $jen = "Pelatihan";
                              } else {
                                $jen = "Pelatihan & Sertifikasi";
                              }
                            ?>
                            <td><?php echo $jen; ?></td>
                          </tr>
                          <tr>
                            <td>Status Peserta</td>
                            <?php
                              if($data['status_peserta']==1) {
                                $stat_pes = "Guru";
                              } else if($data['status_peserta']==2) {
                                $stat_pes = "Siswa";
                              } else {
                                $stat_pes = "Umum";
                              }
                            ?>
                            <td><?php echo $stat_pes; ?></td>
                          </tr>
                          <tr>
                            <td>Tingkat Peserta</td>
                            <td><?php echo $data['tingkat_peserta'];?></td>
                          </tr>
                          <tr>
                            <td>Kuota Peserta</td>
                            <td><?php echo $data['kuota'];?></td>
                          </tr>
                          <?php if($data['jenis_pelatihan']!=1){ ?>
                            <tr>
                              <td>KKM</td>
                              <td><?php echo $data['kkm'];?></td>
                            </tr>
                          <?php } ?>
                        </tbody>
                      </table>
                    </div>
                  </div>

                  <br />
                  <?php if ($data['status_pendaftaran']==1) {?>
                  <a class="btn btn-big" href="" onclick="daftar('<?php echo $data['id_pelatihan']?>')">
                      <span>
                          Daftar
                      </span>
                  </a>
                  <?php }?>
              </div><!-- .content end -->
              <?php  $a++;
            } ?>

          </div><!-- .accordion.careers end -->

        </div>
      </div>
  </div>
</div>
<script>

function daftar(id){
  $.post('<?php echo $this->baseUrl()."/user/3e72758f0fc77cdad787f58b41e9985f/daftar/"?>',{key: id}, function(data){
      if(data.edit==true) {
        alert('Anda sudah mendaftar');
        parent.location.href = "<?php echo $this->baseUrl()?>/user/3e72758f0fc77cdad787f58b41e9985f/certification";
      } else {
          alert('Gagal mendaftar');
      }
  });

}
</script>
