<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="custom-heading">
              <h2>Ini Title</h2>
          </div><!-- .custom-heading end -->
          <div class="content">
            <div class="post-date">
              <p>
                <i class="fa fa-calendar"></i>
                2016-04-25 18:33:42 (cuma contoh)
              </p>
            </div>
            <p>
              deskripsi
            </p>
            <div class="col-md-5">
            <div class="table-responsive">
              <table class="table">
                <thead></thead>
                <tbody>
                  <tr>
                    <td>Gelombang</td>
                    <td>1</td>
                  </tr>
                  <tr>
                    <td>Jenis Pelatihan</td>
                    <td>Pelatihan Biasa/Sertifikasi</td>
                  </tr>
                  <tr>
                    <td>Status Peserta</td>
                    <td>Guru/Murid/Umum</td>
                  </tr>
                  <tr>
                    <td>Tingkat Peserta</td>
                    <td>TK/SD/SMP/Dst</td>
                  </tr>
                  <tr>
                    <td>Kuota Peserta</td>
                    <td>10</td>
                  </tr>
                  <!-- ini utk yg jenisnya sertifikasi muncul van -->
                  <tr>
                    <td>KKM</td>
                    <td>70</td>
                  </tr>
                  <!-- end -->
                </tbody>
              </table>
              <div class="wpcf7">
                <div class="wpcf7-submit">
                  Daftar
                </div>
              </div>
            </div>

          </div>
          </div>
        </div>
      </div>
  </div>
</div>
