<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="custom-heading">
              <h2>Hasil Nilai</h2>
          </div><!-- .custom-heading end -->
          <div class="table-responsive">
              <table class="events-table" style="width:100%;">
                  <thead>
                      <tr>
                          <th>No</th>
                          <th>Program</th>
                          <th>KKM</th>
                          <th>Nilai</th>
                          <th>Status</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr style="border-bottom: 1px solid #e6e6e6;">
                        <td>1.</td>
                        <td>
                          Pelatihan Asesor Kompetensi dan Lisensi Otomotif
                        </td>
                        <td>65</td>
                        <td>80</td>
                        <td>Lulus</td>
                      </tr>

                      <tr style="border-bottom: 1px solid #e6e6e6;">
                        <td>2.</td>
                        <td>
                          Pelatihan Asesor Kompetensi dan Lisensi Akuntansi
                        </td>
                        <td>65</td>
                        <td>80</td>
                        <td>Lulus</td>
                      </tr>
                  </tbody>
              </table><!-- .events-table end -->
            </div>
        </div>
      </div>
  </div>
</div>
