<div class="page-content">
  <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="custom-heading">
              <h2>Ubah Password</h2>
              <?php
                  if($this->message != '') {
                    echo $this->message;
                  }
              ?>
          </div><!-- .custom-heading end -->
          <form class="login-form wpcf7" action="#" method="post" enctype="multipart/form-data">
            <fieldset>
              <label for="pass_lama">Password Lama <span class="required">*</span></label>
              <input type="password" name="pass_lama" id="pass_lama" value="" class="input-text wpcf7-text" required="required">
            </fieldset>
            <fieldset>
              <label for="password">Password <span class="required">*</span></label>
              <input type="password" name="password" id="password" value="" class="input-text wpcf7-text" required="required">
            </fieldset>
            <fieldset>
              <label for="confirm">Confrim Password <span class="required">*</span></label>
              <input type="password" name="confirm" id="confirm" value="" class="input-text wpcf7-text" required="required">
            </fieldset>
            <input type="submit" class="wpcf7-submit" value="Ubah Password" />
          </form>
        </div>
      </div>
  </div>
</div>
