<html>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"></script>
<script type="text/javascript">

	$(function() {
		$("table").tablesorter({debug: true})
		$("a.append").click(appendData);


	});

</script>
	<body>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
		<div class="panel panel-info">
		<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i>&nbsp;<b>LIST KOMENTAR</b>
		</div>
		<table class="table">
		        <thead>
		          <tr align="center">
		          	<th width="100">No</th>
								<th>Nama Lengkap</th>
		            <th>Email</th>
		            <th>Date Created</th>
		            <th colspan="2">Action</th>
		          </tr>
		        </thead>
		        <tbody>
		         <?php for($a=0;$a < count($this->detail);$a++){
		         	$b = $a+1;
		         		?>
		         <tr>
		         	<td><?php echo $b;?></td>
							<td><?php echo $this->detail[$a]['nama'];?></td>
		         	<td><?php echo $this->detail[$a]['email'];?></td>
		         	<td><?php echo $this->detail[$a]['tgl'];?></td>
		         	<td width="50px">
								<a class="btn btn-default btn-lg active" href="<?php echo $this->baseUrl();?>/admin/contact/detail/p/<?php echo $this->detail[$a]['id_kontak']?>" style="cursor: pointer;">
									<span class="glyphicon glyphicon-edit"> View</span>
								</a>
							</td>
		         	<td width="50px">
								<a class="btn btn-default btn-lg active" style="cursor: pointer;" onclick="hps('<?php echo $this->detail[$a]['id_kontak']?>')">
								<span class="glyphicon glyphicon-remove-circle"> Delete</span>
							</a>
							</td>
		         </tr>
		         <?php }?>
		        </tbody>
		        <tfoot>
		        </tfoot>
		      </table>

		      </form>
		</div>

		<script>

		function hps(id){
			$.post('<?php echo $this->baseUrl()."/admin/contact/delete/id"?>',{key: id}, function(data){
		          if(data.edit==true) {
					alert('Data Clear');
					parent.location.href = "<?php echo $this->baseUrl()?>/admin/contact/index";
			      } else {
			    	  alert('Failed Clear Data');
			      }
		      });

		}
		</script>
	</body>
</html>
