<div class="header-wrapper style03">
  <!-- .header.header-style02 start -->
  <header id="header"  class="header-style03">
      <div class="logo-info-container">
          <div class="container">
              <div class="row">
                  <div class="col-md-6">
                      <div class="logo">
                          <a href="<?php echo $this->baseUrl();?>/index">
                              <img src="img/logo.png" alt="P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN"/>
                          </a>
                      </div><!-- .logo end -->
                  </div><!-- .col-md-6 end -->

                  <div class="col-md-6">
                      <div class="info-container">
                          <ul id="quick-links" class="clearfix">
                              <li>
                                  <i class="fa fa-phone"></i>
                                  <span>+00 41 895 785 6985</span>
                              </li>

                              <li>
                                  <i class="fa fa-envelope"></i>
                                  <a href="contact-simple.html">Contact us today</a>
                              </li>
                          </ul><!-- .quick links end -->

                          <!-- #search start -->
                          <div id="search">
                              <form action="#" method="get">
                                  <input class="search-submit" type="submit" />
                                  <input id="m_search" name="s" type="text" placeholder="Type and hit enter..." />
                              </form>
                          </div><!-- #search end -->
                      </div><!-- .info-container end -->
                  </div><!-- .col-md-6 end -->
              </div><!-- .row end -->
          </div><!-- .container end -->
      </div><!-- .logo-info-container end -->

      <?php include("../application/views/scripts/include/menu.phtml"); ?>

  </header><!-- .header.header-style02 -->
</div><!-- .header-wrapper end -->
