<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i> <b>EDIT PHOTO</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
  <div class="form-group">
	    <label for="nama" class="col-sm-2 control-label">Judul Photo</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama" value="<?php echo $this->det[0]['nama'];?>">
	      <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $this->det[0]['id_foto'];?>">
	    </div>
  </div>
  <div class="form-group">
  <label for="foto" class="col-sm-2 control-label">Photo</label>
  <div class="col-sm-10">
      <input type="file" name="file" id="file">
      <p class="help-block">Add image here.</p>
      <input type="hidden" class="form-control" id="image" name="image" value="<?php echo $this->det[0]['url'];?>">
  </div>
 </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/galeri/photo'">Cancel</button>
    </div>
  </div>
</div>
</form>
</div>
</html>
