<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Pelatihan dan Sertifikasi
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
    <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="custom-heading">
                <h2>Jadwal Pelatihan dan Sertifikasi P2KGK di Tahun 2016</h2>
            </div><!-- .custom-heading end -->
            <div class="table-responsive">
                <table class="events-table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tanggal</th>
                            <th>Gelombang</th>
                            <th>Program</th>
                            <th>Peserta</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="border-bottom: 1px solid #e6e6e6;">
                            <td>1.</td>
                            <td class="event-date p2kgkdate">
                                25/05/2016 s.d 29/05/2016
                            </td>
                            <td>Gelombang 1</td>
                            <td>
                                <ol>
                                  <li>Pelatihan Junior Network Administration dan Sertifikasi Junior Network Administrator</li>
                                  <li>Pelatihan Junior Programmer dan Sertifikasi Junior Programmer</li>
                                </ol>
                            </td>
                            <td>
                                Guru TIK SMA
                            </td>
                            <td>
                                Pendaftaran masih buka
                            </td>
                        </tr>

                        <tr style="border-bottom: 1px solid #e6e6e6;">
                            <td>2.</td>
                            <td class="event-date p2kgkdate">
                                25/05/2016 s.d 29/05/2016
                            </td>
                            <td>Gelombang 1</td>
                            <td>
                                <ol>
                                  <li>Pelatihan Junior Network Administration dan Sertifikasi Junior Network Administrator</li>
                                  <li>Pelatihan Junior Programmer dan Sertifikasi Junior Programmer</li>
                                </ol>
                            </td>
                            <td>
                                Guru TIK SMA
                            </td>
                            <td>
                                Pendaftaran masih buka
                            </td>
                        </tr>
                    </tbody>
                </table><!-- .events-table end -->
              </div>
          </div>
        </div>
    </div>
</div>
