<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Sertifikasi
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
    <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="custom-heading">
                <h2>Jadwal Sertifikasi P2KGK di Tahun 2016</h2>
            </div><!-- .custom-heading end -->
            <div class="table-responsive">
                <table class="events-table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tanggal</th>
                            <th>Gelombang</th>
                            <th>Nama Pelatihan</th>
                            <th>Program</th>
                            <th>Peserta</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                      <?php
                      $no=1;
                      foreach ($this->data as $pel) { ?>
                        <tr style="border-bottom: 1px solid #e6e6e6;">
                            <td><?php echo $no;?></td>
                            <td class="event-date p2kgkdate">
                                <?php echo $pel['tgl'];?>
                            </td>
                            <td>Gelombang <?php echo $pel['gelombang'];?></td>
                            <td>
                                <?php echo $pel['nama_pelatihan'];?>
                            </td>
                            <td>
                                <?php echo $pel['deskripsi'];?>
                            </td>
                            <td>
                                  <?php echo $pel['tingkat_peserta'];?>
                            </td>
                            <td>
                                <?php
                                if($pel['status_pendaftaran']==1) {
                                  echo "Pendaftaran masih buka";
                                } else {
                                  echo "<span style='color:#f00;'>Pendaftaran sudah tutup</span>";
                                }
                                ?>
                            </td>
                        </tr>
                        <?php $no++;} ?>
                    </tbody>
                </table><!-- .events-table end -->
              </div>
          </div>
        </div>
    </div>
</div>
