<div class="column column-wide">
  <div class="widget">
    <!-- isi profile -->
    <?php
    	//Zend_Debug::dump($this->data);die();
    	// if ($this->data!=null) {
      //   echo '<h1>'.$this->data[0]['nama_profil'].'</h1>';
    	// 	if($this->data[0]['gambar']!='') {
    	// 		/* disini kalo mo ngasih style jak buat picturenya...src nya $this->baseUrl()/img/Profile/thisdatanya */
    	// 		echo '<img src="'.$this->baseUrl().'/img/Profile/'.$this->data[0]['gambar'].'"/>';
    	// 	}
    	// 	echo $this->data[0]['konten'];
    	// } else {
    	// 	echo 'content empty!';
    	// }
    ?>
    <!-- isi sementara -->
    <ol style="list-style-type:upper-alpha;">
	<li><strong>Kemitraan Stakeholder dan DU/DI di P2KGK</strong></li>
</ol>

<ol>
	<li>PT. Nenggalamas Cipta Presisi (DU/DI pada Pelatihan Kewirausahaan Teknisi Handphone)</li>
	<li>LIA (Narasumber)</li>
	<li>LPIA (Narasumber)</li>
	<li>UNJ (Narasumber)</li>
</ol>

    <!-- end isi -->
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
