<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Kemitraan
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<?php
  //Zend_Debug::dump($this->data);die();
  // if ($this->data!=null) {
  //   echo '<h1>'.$this->data[0]['nama_profil'].'</h1>';
  // 	if($this->data[0]['gambar']!='') {
  // 		/* disini kalo mo ngasih style jak buat picturenya...src nya $this->baseUrl()/img/Profile/thisdatanya */
  // 		echo '<img src="'.$this->baseUrl().'/img/Profile/'.$this->data[0]['gambar'].'"/>';
  // 	}
  // 	echo $this->data[0]['konten'];
  // } else {
  // 	echo 'content empty!';
  // }
?>
<div class="page-content">
    <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="custom-heading">
                <h2>Kemitraan Stakeholder dan DU/DI di P2KGK</h2>
            </div><!-- .custom-heading end -->
            <p>
              <ol>
              	<li>PT. Nenggalamas Cipta Presisi (DU/DI pada Pelatihan Kewirausahaan Teknisi Handphone)</li>
              	<li>LIA (Narasumber)</li>
              	<li>LPIA (Narasumber)</li>
              	<li>UNJ (Narasumber)</li>
              </ol>
            </p>
          </div>
        </div>
    </div>
</div>
