<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Program Pelatihan
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<?php
  //Zend_Debug::dump($this->data);die();
  // if ($this->data!=null) {
  //   echo '<h1>'.$this->data[0]['nama_profil'].'</h1>';
  // 	if($this->data[0]['gambar']!='') {
  // 		/* disini kalo mo ngasih style jak buat picturenya...src nya $this->baseUrl()/img/Profile/thisdatanya */
  // 		echo '<img src="'.$this->baseUrl().'/img/Profile/'.$this->data[0]['gambar'].'"/>';
  // 	}
  // 	echo $this->data[0]['konten'];
  // } else {
  // 	echo 'content empty!';
  // }
?>
<div class="page-content">
    <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="custom-heading">
                <h2>Program-Program Pelatihan Kompetensi Guru di P2KGK</h2>
            </div><!-- .custom-heading end -->
            <p>
              <p>&nbsp;</p>

              <ol>
              	<li>Pengembangan Kompetensi Guru Inklusi bagi Guru SD, SMP, SMA/SMK;</li>
              	<li>Pengembangan Peningkatan Kompetensi Guru Agama SD, SMP, SMA/SMK;</li>
              	<li>Pengembangan Peningkatan Kompetensi Guru BK SD, SMP, SMA/SMK;</li>
              	<li>Pengembangan Peningkatan Kompetensi Guru SD, SMP, SMA/SMK;</li>
              	<li>Pelatihan Analisis Materi Essensial Mata Pelajaran UN SD, SMP, SMA/SMK;</li>
              </ol>

              <ol>
              	<li>Pelatihan Asesor Kompetensi dan Lisensi Bidang Keahlian Ketenaga Listrikan;</li>
              	<li>Pelatihan Asesor Kompetensi dan Lisensi Bidang Keahlian Administrasi Perkantoran;</li>
              	<li>Pelatihan Asesor Kompetensi dan Lisensi Bidang Keahlian Komputer Informatika;</li>
              	<li>Pelatihan Asesor Kompetensi dan Lisensi Otomotif;</li>
              	<li>Pelatihan Asesor Kompetensi dan Lisensi Permesinan;</li>
              	<li>Pelatihan Asesor Kompetensi dan Lisensi Akuntansi;</li>
              	<li>Pelatihan Asesor Metodologi Bidang Keahlian Ketenaga Listrikan;</li>
              	<li>Pelatihan Asesor Metodologi Kompetensi Bidang Keahlian Permesinan;</li>
              	<li>Pelatihan Asesor Metodologi Bidang Keahlian Akuntansi ;</li>
              	<li>Pelatihan Asesor Metodologi Bidang Keahlian Otomotif ;</li>
              	<li>Pelatihan Asesor Metodologi Bidang Keahlian Teknik Komputer Jaringan;</li>
              	<li>Pelatihan Asesor Metodologi Bidang Keahlian Administrasi Perkantoran;</li>
              	<li>Pelatihan Kewirausahaan Teknik tune up EFI Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pelatihan Komputer Accurate Manufacture Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pelatihan Komputer Akuntasi Perpajakan Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pelatihan Membuat Program PLC Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pelatihan Model-Model Pembelajaran Jenjang SD, SMP, SMA/SMK;</li>
              	<li>Pelatihan Motivasi dan Pembangunan Karakter Bagi Guru SD, SMP, SMA/SMK;</li>
              	<li>Pelatihan Multimedia Dasar dan Internet Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pelatihan Multimedia Lanjutan dan Internet Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan ;</li>
              	<li>Pelatihan Penelitian Tindakan Kelas (PTK) Bagi Guru SD, SMP, SMA/SMK;</li>
              	<li>Pelatihan Pengembangan Keprofesian Berkelanjutan Bagi Guru SD, SMP,SMA/SMK;</li>
              	<li>Pelatihan Peningkatan Kompetensi Persiapan Sertifikasi Bagi Guru SD, SMP, SMA/SMK;</li>
              	<li>Pelatihan Sistem Pendingin AC Mobil Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pelatihan Spooring dan Balancing Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>pelatihan Teknik Pengelasan Building Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pelatihan Test Bent Bekerjasama Dengan DU/DI Untuk Guru SMK Kejuruan;</li>
              	<li>Pembentukan LSP Lanjutan.</li>
              	<li>Ahli Fungsi Guru Bidang Study dan Guru Pembimbing Khusus (GPK) Inklusif;</li>
              	<li>Bimtek Kemampuan Dasar (Calistung) Guru kelas II;</li>
              	<li>Bimtek Penyusunan Soal Ulangan Kenaikan Kelas (UKK) SDLB/SMPLB/SMALB;</li>
              	<li>Bimtek Tim Pengembang Kurikulum SD, SMP, SMA, dan SMK;</li>
              	<li>Lomba Penelitian Tindakan Kelas Guru Tingkat Provinsi DKI Jakarta;</li>
              	<li>Pelatihan Metode Hitung Cepat Kepada Guru Sekolah;</li>
              	<li>Pelatihan Pembinaan Guru/Siswa Terhadap Lagu-Lagu Daerah dan Lagu Wajib Nasional;</li>
              	<li>Penyelenggaraan Tes Diagnostik Guru Kelas IV, V, dan VI SD;</li>
              	<li>Pelatihan Pembelajaran Guru TK;</li>
              </ol>

              <p>&nbsp;</p>

              <ol style="list-style-type:upper-alpha;">
              	<li value="2"><strong>Program-Program Pelatihan Kejuruan di P2KGK</strong></li>
              </ol>

              <ol>
              	<li><strong>Kategori Bengkel </strong></li>
              </ol>

              <ul>
              	<li><strong>Listrik (Instalasi Rumah/Instalasi Tenaga/PLC)</strong></li>
              </ul>

              <ul>
              	<li>Pelatihan dan Praktek Ketenagalistrikan;</li>
              	<li>Pelatihan dan Sertifikasi Siswa SMK Kompetensi Keahlian Teknis Listrik;</li>
              	<li>Pelatihan Kewirausahaan Teknik Pendingin AC dan Tata Udara Dasar Bekerjasama Dengan Asosiasi Untuk Siswa SMK Program Studi Keahlian Teknik Ketenagalistrikan dan Elektronika;</li>
              </ul>

              <p style="margin-left:1.5in;">&nbsp;</p>

              <ul>
              	<li><strong>Mesin (Bubut/CNC/Las)</strong></li>
              </ul>

              <ul>
              	<li>Pelatihan dan Praktek Operator Mesin CNC;</li>
              	<li>Pelatihan dan Praktek Teknik Permesinan;</li>
              	<li>Pelatihan dan Sertifikasi Siswa SMK Kompetensi Teknik Las;</li>
              	<li>Pelatihan High Speed Untuk Siswa SMK;</li>
              	<li>Pelatihan Mesin High Speed Precision Lathe dan Mesin Surface Grinder Bekerjasama Dengan DU/DI Untuk Siswa SMK Program Keahlian Teknik Mesin;</li>
              	<li>Pelatihan Surface Grinder Siswa SMK;</li>
              </ul>

              <p style="margin-left:1.5in;">&nbsp;</p>

              <ul>
              	<li><strong>Otomotif (Evi/Kendaraan Ringan)</strong></li>
              </ul>

              <ul>
              	<li>Pelatihan dan Praktek Casis Kendaraan Ringan;</li>
              	<li>Pelatihan dan Praktek Kendaraan Ringan Tune Up EFI;</li>
              	<li>Pelatihan dan Sertifikasi Siswa SMK Kompetensi Teknik Sepeda Motor;</li>
              	<li>Pelatihan dan Sertifikasi Siswa SMK Kompetensi Teknik Kendaraan Ringan;</li>
              	<li>Pelatihan Kewirausahaan Teknisi Sepeda Motor Bekerjasama Dengan DU/DI Untuk Siswa SMK Program Keahlian Teknik Otomotif;</li>
              	<li>Pelatihan Kewirausahaan Teknik Tune Up EFI Bekerjasama Dengan DU/DI Untuk Siswa SMK Program Keahlian Teknik Otomotif;</li>
              </ul>

              <p style="margin-left:1.5in;">&nbsp;</p>

              <ul>
              	<li><strong>Elektro (Audio/Vidio)</strong></li>
              </ul>

              <ul>
              	<li>Pelatihan dan Praktek Teknik Audio Video;</li>
              </ul>

              <p style="margin-left:1.0in;">&nbsp;</p>

              <p style="margin-left:1.0in;">&nbsp;</p>

              <p style="margin-left:1.0in;">&nbsp;</p>

              <ol>
              	<li value="2"><strong>Kategori Bidang/Jurusan </strong></li>
              </ol>

              <ul>
              	<li><strong>Multimedia</strong></li>
              </ul>

              <ul>
              	<li>Pelatihan Kewirausahaan Teknisi Handphone Bekerjasama Dengan DU/DI Untuk Siswa SMK Program Keahlian Teknik Elektronika dan Multimedia;</li>
              	<li>Pelatihan Kewirausahaan Upgrading Software Hardware Handphone Bekerjasama Dengan DU/DI Untuk Siswa SMK Program Keahlian Teknik Elektornika Multimedia;</li>
              	<li>Pelatihan dan Praktek Multimedia;</li>
              	<li>Pelatihan dan Sertifikasi Siswa SMK Kompetensi Komputer dan Jaringan;</li>
              	<li>Pelatihan Photography;</li>
              	<li>Pelatihan Kewirausahaan Grafik Desain dan Web Desain Bekerjasama Dengan DU/DI Untuk Siswa SMK Program Keahlian Teknik Elektronika dan Multimedia;</li>
              </ul>

              <p style="margin-left:1.5in;">&nbsp;</p>

              <ul>
              	<li><strong>Administrasi Perkantoran</strong></li>
              </ul>

              <ul>
              	<li>Pelatihan dan Praktek Administrasi Perkantoran dan Administrasi Akuntansi;</li>
              	<li>Pelatihan dan Sertifikasi Siswa SMK Kompetensi Keahlian Administrasi Perkantoran;</li>
              	<li>Pelatihan Microsoft Office;</li>
              </ul>

              <p style="margin-left:1.5in;">&nbsp;</p>

              <ul>
              	<li><strong>Akuntansi</strong></li>
              </ul>

              <ul>
              	<li>Pelatihan dan Sertifikasi Siswa SMK Kompetensi Keahlian Administrasi Akuntansi;</li>
              </ul>
            </p>
          </div>
        </div>
    </div>
</div>
