<div class="column column-wide">
  <div class="widget">
    <!-- isi profile -->
    <?php
    	//Zend_Debug::dump($this->data);die();
    	// if ($this->data!=null) {
      //   echo '<h1>'.$this->data[0]['nama_profil'].'</h1>';
    	// 	if($this->data[0]['gambar']!='') {
    	// 		/* disini kalo mo ngasih style jak buat picturenya...src nya $this->baseUrl()/img/Profile/thisdatanya */
    	// 		echo '<img src="'.$this->baseUrl().'/img/Profile/'.$this->data[0]['gambar'].'"/>';
    	// 	}
    	// 	echo $this->data[0]['konten'];
    	// } else {
    	// 	echo 'content empty!';
    	// }
    ?>
    <!-- isi sementara -->
    <ol style="list-style-type:upper-alpha;">
	<li><strong>Fasilitas Sarana dan Prasarana di P2KGK</strong></li>
</ol>

<ol>
	<li>Gedung yang beralamat di Jl. Sawah Barat Duren Sawit Jakarta Timur</li>
	<li>Peralatan mesin penunjang untuk jurusan :
	<ul>
		<li>Tekhnik Otomotof</li>
		<li>Teknik Permesinan</li>
		<li>Teknik Informatika</li>
		<li>Teknik Kelistrikan</li>
		<li>Teknik Elektronika</li>
		<li>Bisnis Manajeman</li>
	</ul>
	</li>
</ol>

<ol>
	<li value="3">Gedung baru dalam proses penyelesaian, kondisi 85 %</li>
</ol>

    <!-- end isi -->
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
