<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <h1>P2KGK - Agenda</h1>
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Agenda
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content p2kgknews">
    <div class="container">
        <div class="row">
            <ul class="col-md-9 blog-posts post-list">
              <?php foreach ($this->data as $agenda) { ?>

                <li class="blog-post clearfix">
                    <div class="post-date">
                      <?php
                        $yrdata= strtotime($agenda['waktu']);
                        $m = date('M Y', $yrdata);
                        $t = date('H:i', $yrdata);
                        $d = date('d', $yrdata);
                      ?>
                        <p class="day"><?php echo $d; ?></p>
                        <p class="month"><?php echo $m; ?></p>
                        <p class="time"><i class="fa fa-clock-o"></i> <?php echo $t; ?></p>
                    </div><!-- .post-date end -->

                    <div class="post-body">
                        <a href="<?php echo $this->baseUrl();?>/agenda/detail/p/<?php echo $agenda['id_agenda']?>">
                            <h3><?php echo $agenda['judul'];?></h3>
                        </a>

                        <p>
                            <?php echo $agenda['isi'];  ?>
                        </p>

                        <a href="<?php echo $this->baseUrl();?>/agenda/detail/p/<?php echo $agenda['id_agenda']?>" class="read-more">
                            <span>
                                Read more
                                <i class="fa fa-chevron-right"></i>
                            </span>
                        </a>
                    </div><!-- .post-body end -->
                </li><!-- .blog-post end -->
                <?php } ?>

              </ul>
          </div>
      </div>
</div>
