<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i> <b>ADD NEW JABATAN</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
  <div class="form-group">
	    <label for="nama" class="col-sm-2 control-label">Nama Jabatan</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama">
	    </div>
  </div>
  <div class="form-group">
	    <label for="tingkat" class="col-sm-2 control-label">Tingkat Sekolah</label>
	    <div class="col-sm-10">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="TK" name="tingkat[]">TK
          </label>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="SD" name="tingkat[]">SD
          </label>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="SMP" name="tingkat[]">SMP
          </label>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="SMA" name="tingkat[]">SMA
          </label>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="SMK" name="tingkat[]">SMK
          </label>
        </div>
	    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/master/jabatan'">Cancel</button>
    </div>
  </div>
</div>
</form>
</div>
</html>
