<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i> <b>EDIT SEKOLAH</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
  <h5>Edit sekolah hanya bisa mengganti nama, alamat dan kelurahan. Bila ingin mengganti lebih disarankan membuat baru</h5>
  <div class="form-group">
	    <label for="id" class="col-sm-2 control-label">No Induk Sekolah</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" readonly="readonly" id="id" name="id" value="<?php echo $this->det[0]['induk_sekolah'];?>">
	    </div>
  </div>
  <div class="form-group">
	    <label for="nama" class="col-sm-2 control-label">Nama Sekolah</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama" value="<?php echo $this->det[0]['nama_sekolah'];?>">
	    </div>
  </div>
  <div class="form-group">
	    <label for="alamat" class="col-sm-2 control-label">Alamat Sekolah</label>
	    <div class="col-sm-10">
        <textarea name="alamat" id="alamat" rows="8" cols="40" class="input-text form-control"><?php echo $this->det[0]['alamat'];?></textarea>
	    </div>
  </div>
  <div class="form-group">
	    <label for="kelurahan" class="col-sm-2 control-label">Kelurahan</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="kelurahan" name="kelurahan" value="<?php echo $this->det[0]['kelurahan'];?>">
	    </div>
  </div>
  <div class="form-group">
    <label for="kec" class="col-sm-2 control-label">Kecamatan</label>
    <div class="col-sm-10">
      <select name="kec" id="kec" disabled class="input-text form-control kecamatan">
        <option value="">-- Pilih Kecamatan --</option>
        <?php
        $listkec = new Admin_Model_MasterModel();
        $kecamatan = $listkec->getKecamatanlist();
        foreach ($kecamatan as $kec ) {
        ?>
        <option value="<?php echo $kec['id_kec']?>" <?php if ($this->det[0]['id_kecamatan'] == $kec['id_kec']) echo "selected"; ?>><?php echo $kec['nama_kec']?></option>
        <?php } ?>
      </select>
    </div>
  </div>
  <div class="form-group">
	    <label for="tingkat" class="col-sm-2 control-label">Tingkat Sekolah</label>
	    <div class="col-sm-10">
        <select id="tingkat" name="tingkat" class="form-control" disabled>
          <option value="">-- Pilih Tingkat Sekolah --</option>
          <option value="TK" <?php if ($this->det[0]['tingkat'] == "TK") echo "selected"; ?>>TK</option>
					<option value="SD" <?php if ($this->det[0]['tingkat'] == "SD") echo "selected"; ?>>SD</option>
					<option value="SMP" <?php if ($this->det[0]['tingkat'] == "SMP") echo "selected"; ?>>SMP</option>
					<option value="SMA" <?php if ($this->det[0]['tingkat'] == "SMA") echo "selected"; ?>>SMA</option>
					<option value="SMK" <?php if ($this->det[0]['tingkat'] == "SMK") echo "selected"; ?>>SMK</option>
        </select>
	    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/master/sekolah'">Cancel</button>
    </div>
  </div>
</div>
</form>
</div>
</html>
