<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i> <b>EDIT GURU</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
	<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
    <div class="form-group">
	    <label for="nip" class="col-sm-2 control-label">NIP</label>
	    <div class="col-sm-10">
        <input type="text" name="nip" id="nip" class="input-text form-control" value="<?php echo $this->det[0]['nip'];?>">
	    </div>
  	</div>
    <div class="form-group">
	    <label for="nama" class="col-sm-2 control-label">Nama Lengkap</label>
	    <div class="col-sm-10">
        <input type="text" name="nama" id="nama" class="input-text form-control" value="<?php echo $this->det[0]['nama_lengkap'];?>">
	    </div>
  	</div>
    <div class="form-group">
	    <label for="tlp" class="col-sm-2 control-label">No Tlp</label>
	    <div class="col-sm-10">
        <input type="text" name="tlp" id="tlp" class="input-text form-control" value="<?php echo $this->det[0]['no_tlp'];?>">
	    </div>
  	</div>
    <div class="form-group">
	    <label for="email" class="col-sm-2 control-label">Email</label>
	    <div class="col-sm-10">
        <input type="text" name="email" id="email" class="input-text form-control" value="<?php echo $this->det[0]['email'];?>">
	    </div>
  	</div>
    <div class="form-group">
      <label for="alamat" class="col-sm-2 control-label">Alamat</label>
      <div class="col-sm-10">
        <textarea name="alamat" id="alamat" rows="8" cols="40" class="input-text form-control"><?php echo $this->det[0]['alamat'];?></textarea>
      </div>
    </div>
    <div class="form-group">
	    <label for="jenis_sek" class="col-sm-2 control-label">Jenis Sekolah</label>
	    <div class="col-sm-10">
        <select name="jenis_sek" id="jenis_sek" class="input-text form-control">
          <option value="1">Reguler</option>
          <option value="3">Paket</option>
        </select>
	    </div>
  	</div>
    <div class="form-group">
	    <label for="jenis_peg" class="col-sm-2 control-label">Kelompok Pegawai</label>
	    <div class="col-sm-10">
        <select name="jenis_peg" id="jenis_peg" class="input-text form-control">
          <option value="G">Tenaga Pendidik</option>
          <option value="P">Tenaga Kependidikan</option>
        </select>
	    </div>
  	</div>
    <div class="form-group">
	    <label for="kec" class="col-sm-2 control-label">Kecamatan</label>
	    <div class="col-sm-10">
        <select name="kec" id="kec" class="input-text form-control">
					<?php
					$listkec = new Admin_Model_MasterModel();
					$kecamatan = $listkec->getKecamatanlist();
					foreach ($kecamatan as $kec ) {
					?>
          <option value="<?php echo $kec['id_kec']?>"><?php echo $kec['nama_kec']?></option>
					<?php } ?>
        </select>
	    </div>
  	</div>
  	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	       <button type="submit" class="btn btn-default">Save</button>
	       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/master/guru'">Cancel</button>
	    </div>
  	</div>
</div>
</form>
</div>
</html>
