<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i> <b>EDIT SISWA</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
	<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
    <div class="form-group">
	    <label for="nis" class="col-sm-2 control-label">NIS</label>
	    <div class="col-sm-10">
        <input type="text" name="nis" id="nis" class="input-text form-control" value="<?php echo $this->det[0]['nis'];?>">
	    </div>
  	</div>
		<div class="form-group">
	    <label for="nip" class="col-sm-2 control-label">Photo</label>
	    <div class="col-sm-5">
        <img src="" alt="" />
	    </div>
  	</div>
    <div class="form-group">
	    <label for="nama" class="col-sm-2 control-label">Nama Lengkap</label>
	    <div class="col-sm-10">
        <input type="text" name="nama" id="nama" class="input-text form-control" value="<?php echo $this->det[0]['nama_lengkap'];?>">
	    </div>
  	</div>
    <div class="form-group">
	    <label for="tlp" class="col-sm-2 control-label">No Tlp</label>
	    <div class="col-sm-10">
        <input type="text" name="tlp" id="tlp" class="input-text form-control" value="<?php echo $this->det[0]['no_tlp'];?>">
	    </div>
  	</div>
    <div class="form-group">
	    <label for="email" class="col-sm-2 control-label">Email</label>
	    <div class="col-sm-10">
        <input type="text" name="email" id="email" class="input-text form-control" value="<?php echo $this->det[0]['email'];?>">
	    </div>
  	</div>
    <div class="form-group">
      <label for="alamat" class="col-sm-2 control-label">Alamat</label>
      <div class="col-sm-10">
        <textarea name="alamat" id="alamat" rows="8" cols="40" class="input-text form-control"><?php echo $this->det[0]['alamat'];?></textarea>
      </div>
    </div>
		<div class="form-group">
			<label for="jkelamin" class="col-sm-2 control-label">Jenis Kelamin</label>
			<div class="col-sm-10">
				<select name="jkelamin" class="input-text form-control" id="jkelamin">
					<option value="0">-- Pilih --</option>
					<option value="L" <?php if ($this->det[0]['jkelamin'] == "L") echo "selected"; ?>>Laki-laki</option>
					<option value="P" <?php if ($this->det[0]['jkelamin'] == "P") echo "selected"; ?>>Perempuan</option>
				 </select>
		 	</div>
		</div>

    <div class="form-group">
	    <label for="kec" class="col-sm-2 control-label">Kecamatan</label>
	    <div class="col-sm-10">
        <select name="kec" id="kec" class="input-text form-control kecamatan">
					<?php
					$listkec = new Admin_Model_MasterModel();
					$kecamatan = $listkec->getKecamatanlist();
					foreach ($kecamatan as $kec ) {
					?>
          <option value="<?php echo $kec['id_kec']?>" <?php if ($this->det[0]['kec'] == $kec['id_kec']) echo "selected"; ?>><?php echo $kec['nama_kec']?></option>
					<?php } ?>
        </select>
	    </div>
  	</div>
		<div class="form-group">
	    <label for="tingkat_sekolah" class="col-sm-2 control-label">Tingkat Sekolah</label>
	    <div class="col-sm-10">
				<select name="tingkat_sekolah" class="input-text form-control" id="tingkat_sekolah" >
					<option value="TK" <?php if ($this->det[0]['tingkat_sekolah'] == "TK") echo "selected"; ?>>TK</option>
					<option value="SD" <?php if ($this->det[0]['tingkat_sekolah'] == "SD") echo "selected"; ?>>SD</option>
					<option value="SMP" <?php if ($this->det[0]['tingkat_sekolah'] == "SMP") echo "selected"; ?>>SMP</option>
					<option value="SMA" <?php if ($this->det[0]['tingkat_sekolah'] == "SMA") echo "selected"; ?>>SMA</option>
					<option value="SMK" <?php if ($this->det[0]['tingkat_sekolah'] == "SMK") echo "selected"; ?>>SMK</option>
				</select>
	    </div>
  	</div>
		<div class="form-group">
	    <label for="nama_sekolah" class="col-sm-2 control-label">Nama Sekolah</label>
	    <div class="col-sm-10">
				<select name="nama_sekolah" class="input-text form-control namasklh" id="nama_sekolah">
					<option value="0">-- Pilih Tingkat Sekolah dan Kecamatan Dahulu--</option>
				</select>
	    </div>
  	</div>

		<div class="form-group">
	    <label for="status" class="col-sm-2 control-label">Status Sekolah</label>
	    <div class="col-sm-10">
				<select name="status" class="input-text form-control" id="status">
					<option value="0">-- Pilih --</option>
					<option value="1" <?php if ($this->det[0]['status_sek'] == "1") echo "selected"; ?>>Negeri</option>
					<option value="2" <?php if ($this->det[0]['status_sek'] == "2") echo "selected"; ?>>Swasta</option>
				</select>
	    </div>
  	</div>

  	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	       <button type="submit" class="btn btn-default">Save</button>
	       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/master/guru'">Cancel</button>
	    </div>
  	</div>
</div>
</form>
</div>
</html>
<script type="text/javascript">
$( window ).load(function() {
  var tingkat = $('#tingkat_sekolah').val();
  var kec = $('.kecamatan').val();
  var base_url = "<?php echo $this->baseUrl() ?>";
  if(tingkat != 0 && kec != 0) {
    $.ajax({
        type: "POST",
        data: {
            'id_kec' : kec,
            'tingkat' : tingkat,
        },
        url: base_url+"/register/ajaxsekolah",
        success: function(data){
          var sekolah = '';
          for(j=0; j < data.data.length;j++){
             sekolah+='<option value='+data.data[j]['induk_sekolah']+'>'+data.data[j]['nama_sekolah']+'</option>';
           }
           $('.namasklh').html(sekolah);
           $(".namasklh option[value=<?php echo $this->det[0]['nama_sekolah'];?>]").attr('selected','selected');

         }
    });
  }
  $('.kecamatan, #tingkat_sekolah').change(function() {
    var tingkat = $('#tingkat_sekolah').val();
    var kec = $('.kecamatan').val();
    var base_url = "<?php echo $this->baseUrl() ?>";
    if(tingkat != 0 && kec != 0) {
      $.ajax({
          type: "POST",
          data: {
              'id_kec' : kec,
              'tingkat' : tingkat,
          },
          url: base_url+"/register/ajaxsekolah",
          success: function(data){
            var sekolah = '';
            for(j=0; j < data.data.length;j++){
               sekolah+='<option value='+data.data[j]['induk_sekolah']+'>'+data.data[j]['nama_sekolah']+'</option>';
             }
             $('#nama_sekolah').html(sekolah);

           }
      });
    }
  });
});
</script>
