<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i> <b>EDIT MATA PELAJARAN</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
	<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
	<div class="form-group">
	    <label for="nama" class="col-sm-2 control-label">Nama Mata Pelajaran</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama" value="<?php echo $this->det[0]['nama_mapel'];?>">
	      <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $this->det[0]['id_mapel'];?>">
	    </div>
  	</div>
    <div class="form-group">
  	    <label for="tingkat" class="col-sm-2 control-label">Tingkat Sekolah</label>
  	    <div class="col-sm-10">
          <select class="form-control" name="tingkat" id="tingkat">
            <option value="">-- Pilih Tingkat Sekolah --</option>
            <option <?php if ($this->det[0]['jenis_sekolah'] == "TK") echo "selected"; ?> value="TK">TK</option>
            <option <?php if ($this->det[0]['jenis_sekolah'] == "SD") echo "selected"; ?> value="SD">SD</option>
            <option <?php if ($this->det[0]['jenis_sekolah'] == "SMP") echo "selected"; ?> value="SMP">SMP</option>
            <option <?php if ($this->det[0]['jenis_sekolah'] == "SMA") echo "selected"; ?> value="SMA">SMA</option>
            <option <?php if ($this->det[0]['jenis_sekolah'] == "SMK") echo "selected"; ?> value="SMK">SMK</option>
          </select>
  	    </div>
    	</div>
  	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	       <button type="submit" class="btn btn-default">Save</button>
	       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/master/mapel'">Cancel</button>
	    </div>
  	</div>
</div>
</form>
</div>
</html>
