<html>
	<body>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
		<div class="panel panel-info">
		<div class="panel-heading" style="display:inline-block;">
      <i class="glyphicon glyphicon-dashboard"></i>&nbsp;<b>MASTER DATA SEKOLAH SELURUH JAKARTA TIMUR</b>
			<div class="col-lg-6" style="float:right;position: relative;left: 30px;bottom: 6px;">
				<div class="input-group pull-right">
          <a class="btn btn-success btn-lg" href="<?php echo $this->baseUrl();?>/admin/master/addsekolah/" style="cursor: pointer;"><span class="glyphicon glyphicon-plus"> Add Sekolah</span></a>
				</div><!-- /input-group -->
			</div>
      <div class="col-lg-6 pull-right" style="margin-top:15px;">
        <form method="post">
          <div class="row input-group">
            <label for="" style="width:100%; display:inline-block;">Cari Berdasarkan..</label>
            <div class="col-xs-3" style="padding-left:0">
              <select class="form-control" id="category" name="kategori">
                <option value='0'>Pilih Kategori</option>
                <option value='kecamatan'>Kecamatan</option>
                <option value='tingkat'>Tingkat</option>
              </select>
            </div>
            <div class="col-xs-5" style="padding-left:0">
              <select id="key" name="key" class="form-control">
                  <option value="">Pilih kategori dahulu</option>
              </select>
            </div>
            <div class="col-xs-2" style="padding-left:0">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go!</button>
              </span>
            </div>
          </div>
        </form>
      </div>

		</div>
		<table class="table">
		        <thead>
		          <tr align="center">
		          	<th width="100">No</th>
                <th>Induk Sekolah</th>
                <th>Nama Sekolah</th>
                <th>Alamat</th>
                <th>kelurahan</th>
                <th>kecamatan</th>
		            <th>Tingkat</th>
		            <th colspan="2">Action</th>
		          </tr>
		        </thead>
		        <tbody>
		         <?php for($a=0;$a < count($this->detail);$a++){
		         	$b = $a+1;
		         		?>
		         <tr>
		         	<td><?php echo $b;?></td>
              <td><?php echo $this->detail[$a]['induk_sekolah'];?></td>
              <td><?php echo $this->detail[$a]['nama_sekolah'];?></td>
              <td><?php echo $this->detail[$a]['alamat'];?></td>
              <td><?php echo $this->detail[$a]['kelurahan'];?></td>
              <td><?php echo $this->detail[$a]['nama_kec'];?></td>
		         	<td><?php echo $this->detail[$a]['tingkat'];?></td>
		         	<td width="50px">
                <a class="btn btn-default btn-lg active" href="<?php echo $this->baseUrl();?>/admin/master/editsekolah/p/<?php echo $this->detail[$a]['induk_sekolah']?>" style="cursor: pointer;">
                  <span class="glyphicon glyphicon-edit"> Edit</span>
                </a>
              </td>
		         	<td width="50px">
                <a class="btn btn-default btn-lg active" style="cursor: pointer;" onclick="hps('<?php echo $this->detail[$a]['induk_sekolah']?>')">
                  <span class="glyphicon glyphicon-remove-circle"> Delete</span>
                </a>
              </td>
		         </tr>
		         <?php }?>
		        </tbody>
		        <tfoot>
		        </tfoot>
		      </table>

		      </form>
		</div>

		<script>

		function hps(id){
			$.post('<?php echo $this->baseUrl()."/admin/master/delSekolah/"?>',{key: id}, function(data){
          if(data.edit==true) {
						alert('Data Clear');
						parent.location.href = "<?php echo $this->baseUrl()?>/admin/master/sekolah";
		      } else {
			    	  alert('Failed Clear Data');
		      }
      });

		}
		</script>
	</body>
</html>
<div id="option-kec" style="display:none;">
  <?php
  $listkec = new Admin_Model_MasterModel();
  $kecamatan = $listkec->getKecamatanlist();
  foreach ($kecamatan as $kec ) {
    ?>
    <option value="<?php echo $kec['id_kec']?>" <?php if ($this->det[0]['kec'] == $kec['id_kec']) echo "selected"; ?>><?php echo $kec['nama_kec']?></option>
    <?php } ?>
</div>

<script type="text/javascript">
$(document).ready(function() {
  $("#category").change(function () {
      var val = $(this).val();
      var opt = $('#option-kec option').clone();
      if (val == "kecamatan") {
          $("#key").html(opt);
      } else if (val == "tingkat") {
          $("#key").html("<option value='TK'>TK</option><option value='SD'>SD</option><option value='SMP'>SMP</option><option value='SMA'>SMA</option><option value='SMK'>SMK</option>");
      } else {
          $("#key").html('<option value="">Pilih kategori dahulu</option>');
      }
  });
});
</script>
