<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Login Page
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
    <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="custom-heading">
              <h2>Login</h2>
            </div><!-- .custom-heading end -->
            <?php
            if($this->message != '') {
              echo $this->message;
            }
            ?>
            <div class="alert alert-warning" role="alert">
              Bila ingin mendaftar pelatihan dan ujian kompetensi atau melihat hasil ujian online harap melakukan login!<br/>
              Bagi yang belum memiliki akun untuk login, harap melakukan <strong>registrasi/daftar</strong> di samping.
            </div>
            <form class="form-horizontal wpcf7" method="post" action="">
              <fieldset>
                  <label for="inputEmail">
                      <span class="required">*</span> Email
                  </label>
                  <input type="email" name="email" class="form-control wpcf7-text" id="inputEmail" placeholder="Email" required="required">
              </fieldset>
              <fieldset>
                  <label for="inputPassword">
                      <span class="required">*</span> Password
                  </label>
                  <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Password" required="required">
              </fieldset>
              <fieldset>
                  <label for="chooseAkses">
                      <span class="required">*</span> Pilih Akses
                  </label>
                  <select class="form-control" name="akses" required="required">
                    <option value="">-- Pilih Akses --</option>
                    <option value="1">Guru</option>
                    <option value="2">Siswa</option>
                  </select>
              </fieldset>
              <fieldset style="width:auto; display:inline-block;">
                  <div class="required">
                      * Wajib Di isi!
                  </div>
              </fieldset>
              <input type="submit" class="wpcf7-submit" value="Sign in" />
            </form>
            <!-- <div class="alert alert-info" role="alert">
              Belum punya akun? <a href="<?php echo $this->baseUrl();?>/register/" class="alert-link">Daftar Disini!</a>
            </div> -->
          </div>

          <div class="col-md-6">
            <div class="custom-heading">
              <h2>Daftar</h2>
            </div><!-- .custom-heading end -->
            <div class="alert alert-warning" role="alert">
              Silahkan melakukan registrasi sesuai pekerjaan masing-masing pendaftar pada kolom di bawah agar bisa melakukan login.<br/>
              Apabila sudah memiliki akun, silahkan <strong>Login</strong> di samping.
            </div>
            <ul class="service-list-big-icons-details">
              <li>
                <div class="icon-container p2kgk-imgs">
                  <img src="<?php echo $this->baseUrl();?>/img/guru.png" alt="" />
                </div>
                <div class="service-details">
                  <h4>Registrasi Sebagai Guru</h4>
                  <p>
                      Klik <a href="<?php echo $this->baseUrl();?>/register/guru/"><strong>disini</strong></a> untuk mendaftar
                  </p>
                </div>
              </li>
              <li>
                <div class="icon-container p2kgk-imgs">
                  <img src="<?php echo $this->baseUrl();?>/img/murid.png" alt="" />
                </div>
                <div class="service-details">
                  <h4>Registrasi Sebagai Siswa</h4>
                  <p>
                      Klik <a href="<?php echo $this->baseUrl();?>/register/siswa/"><strong>disini</strong></a> untuk mendaftar
                  </p>
                </div>
              </li>
            </ul>
          </div>
        </div>
    </div>
</div>
