<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->baseUrl();?>/img/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->baseUrl();?>/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->baseUrl();?>/img/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->baseUrl();?>/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="<?php echo $this->baseUrl();?>/img/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?php echo $this->baseUrl();?>/img/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

  <link href="<?php echo $this->baseUrl();?>/javascript/chosen/chosen.min.css" media="screen" rel="stylesheet" type="text/css">
    <!-- Bootstrap -->
    <link href="<?php  echo $this->baseUrl();?>/styles/todc/css/bootstrap.min.css" rel="stylesheet">
    <!-- TODC Bootstrap theme -->
    <link href="<?php  echo $this->baseUrl();?>/styles/todc/css/todc-bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="<?php  echo $this->baseUrl();?>/themes/suppli/js/html5shiv.js"></script>
      <script src="<?php  echo $this->baseUrl();?>/themes/supplier/js/respond.min.js"></script>
    <![endif]-->

     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src="<?php  echo $this->baseUrl();?>/styles/todc/js/jquery1-11-0.min.js"></script>
    <script src="<?php  echo $this->baseUrl();?>/styles/todc/js/bootstrap.min.js"></script>
  	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/javascript/chosen/chosen.jquery.min.js"></script>
  	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js"></script>
  	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/jquery-ui-1.10.3.custom.min.css" media="all" />
	  <script src="<?php  echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
    <script src="<?php  echo $this->baseUrl();?>/styles/todc/js/moment.js"></script>
  	<link href="<?php echo $this->baseUrl();?>/fontawesome/css/font-awesome.css" rel="stylesheet">
  	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/tabel-sorter.css" media="all" />
  	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/colorpickerfix/jscolor.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jPages.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl();?>/styles/todc/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/styles/todc/css/bootstrap-datetimepicker.css" />

  <script type="text/javascript">
  $(document).ready(function(){
    $(".dropdown1").hover(function(){
      $(this).addClass("open");
    },function(){
      $(this).removeClass("open");
    });
  });
  </script>
  </head>
  <body>
  <?php
    $session_editor=new Zend_Session_Namespace('session_admin');
  ?>
   <nav class="navbar navbar-masthead navbar-inverse navbar-fixed-top" role="navigation" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".bs-example-masthead-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse bs-example-masthead-collapse-1">
      <?php if($session_editor->roles!='merchant') {?>
      <ul class="nav navbar-nav">
       <li><a href="<?php echo $this->baseUrl()?>/admin/admin/index"><i class="glyphicon glyphicon-dashboard"></i>&nbsp;Dashboard</a></li>
        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/admin/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Admin</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/admin/add">Add New Admin</a></li>
          </ul>
        </li>
        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/#" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Master Data</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/master/kecamatan">Master Kecamatan</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/master/guru">Master Guru</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/master/siswa">Master Siswa</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/master/sekolah">Master Sekolah</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/master/mapel">Master Mata Pelajaran</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/master/jabatan">Master Jabatan</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/master/statuspeg">Master Status Pegawai</a></li>
          </ul>
        </li>
        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/profile/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Profile</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/profile/add">Add New Profile</a></li>
          </ul>
        </li>
        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/news/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;News</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/news/add">Add New News</a></li>
          </ul>
        </li>
        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/artikel/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Artikel</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/artikel/add">Add New Artikel</a></li>
          </ul>
        </li>
        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/agenda/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Agenda</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/agenda/add">Add New Agenda</a></li>
          </ul>
        </li>
        <li class="dropdown1">
          <a href="#" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Laporan</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/laporan/add">Laporan Pelatihan</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/laporan/add">Laporan Sertifikat</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/laporan/add">Laporan Sertifikasi</a></li>
          </ul>
        </li>
        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/galeri/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Media</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/galeri/video">Manage Video</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/galeri/photo">Manage Photo</a></li>
          </ul>
        </li>
      </ul>
        <?php } else {?>
        <ul class="nav navbar-nav">
         <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/lembaga/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Lembaga</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/lembaga/add">Add Nilai</a></li>
          </ul>
        </li>

        <!-- <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/iklan/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Iklan</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/iklan/add">Add New Iklan</a></li>
          </ul>
        </li>


        <li class="dropdown1">
          <a href="<?php echo $this->baseUrl()?>/admin/agenda/index" class="dropdown-toggle1"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Top & Sidebar Menu</a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl()?>/admin/struktur/edit">Struktur</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/welcome/edit">Welcoming Address</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/adart/edit">Ad / Art</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/admin/about/edit">About Us</a></li>
          </ul>
        </li> -->
      </ul>
      <?php }?>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i>&nbsp;
            Welcome,
            <?php
              echo $session_editor->user_id;
            ?>
          <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->baseUrl();?>/admin/loginadmin/logout">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
   <div style="padding: 50px 10px 10px 10px">
    <?php  echo $this->layout()->content;?>
   </div>

  </body>
</html>
