<?php include("../application/views/scripts/include/head.phtml"); ?>

<body class="custom-background">
  <div id="container">
    <?php include("../application/views/scripts/include/header.phtml"); ?>

    <div id="main">
      <div class="wrapper">
        <div class="page-title-style01 pt-bkg11">
          <div class="container">
              <div class="row">
                <div class="col-md-10">
                  <div class="breadcrumb-container">
                    <ul class="breadcrumb">
                      <li>You are here:</li>
                      <li>
                        <a href="<?php echo $this->baseUrl() ?>/user/3e72758f0fc77cdad787f58b41e9985f">Home</a>
                      </li>
                      <li>
                        My Account
                      </li>
                    </ul><!-- .breadcrumb end -->
                  </div><!-- .breadcrumb-container end -->
                </div>
              </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
          <?php 
            $sessionuser = Zend_Registry::get('session_user');
            echo $sessionuser->status;
            if($sessionuser->status=='Guru') {
            include("../application/views/scripts/include/sidebar3.phtml"); 
            } else if($sessionuser->status=='Siswa') {
            include("../application/views/scripts/include/sidebar4.phtml");   
            }
            ?>
            <?php echo $this->layout()->content; ?>
          </div>
        </div>
        <div class="cleaner">&nbsp;</div>
      </div>
    </div>

  </div>
<?php include("../application/views/scripts/include/footer.phtml"); ?>

</body>
</html>
