<footer>
  <div class="wrapper">
    <div class="column column-first">
      <div class="widget wpzoom-custom-menu">
        <p class="title">Info Lainnya</p>
        <div class="menu-menu-lainnya-footer-container">
          <ul id="menu-menu-lainnya-footer" class="menu">
            <li class="menu-item">
              <a target="_blank" href="<?php echo $this->baseUrl();?>/statistik/">Statistik P2KGK</a>
            </li>
          </ul>
        </div>
        <div class="cleaner">&nbsp;</div>
      </div>
      <div class="cleaner">&nbsp;</div>
    </div>
    <div class="column column-second">
      <div class="widget wpzoom-text" >
        <p class="title">Google+</p>
        <div class="textwidget">
          <!-- Tempatkan tag ini di head atau tepat sebelum tag body penutup. -->
          <script src="https://apis.google.com/js/platform.js" async defer>
            {lang: 'id'}
          </script>

          <!-- Tempatkan tag ini di mana pun Anda ingin widget ditampilkan. -->
          <div class="g-person" data-width="212" data-href="https://plus.google.com/110983658397925793542" data-theme="dark" data-rel="author"></div>
        </div>
        <div class="cleaner">&nbsp;</div>
      </div>
      <div class="cleaner">&nbsp;</div>
    </div>
    <div class="column column-third">
      <div class="widget wpzoom-text">
        <p class="title">Facebook</p>
        <div class="textwidget">
          <div class="fb-page" data-href="https://www.facebook.com/P2KGK-Jakarta-Timur-204466053220728" data-width="212" data-height="291" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>
          <div id="fb-root"></div>
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=126278130727907";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
        </div>
        <div class="cleaner">&nbsp;</div>
      </div>
      <div class="cleaner">&nbsp;</div>
    </div>
    <div class="column column-last">
      <div class="widget widget_text" id="text-3">
        <p class="title">Twitter</p>
        <div class="textwidget">
          <a class="twitter-timeline" href="https://twitter.com/p2kgkjaktim" data-widget-id="724216557786660864">Tweets by @p2kgkjaktim</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
        <div class="cleaner">&nbsp;</div>
      </div>
      <div class="cleaner">&nbsp;</div>
    </div>
    <div class="cleaner">&nbsp;</div>
  </div>
</footer>
<div id="footer-copy">
  <div class="wrapper wrapper-copy">
    <p class="copyright">Copyright © 2016 P2KGK Jakarta Timur. All Rights Reserved</p>
    <div class="cleaner">&nbsp;</div>
  </div>
</div>
