<div id="footer-wrapper" class="footer-dark">
    <footer id="footer">
        <div class="container">
            <div class="row">
                <ul class="col-md-3 col-sm-3 footer-widget-container clearfix">
                    <!-- .widget-pages start -->
                    <li class="widget widget_pages">
                        <div class="title">
                            <h3>quick links</h3>
                        </div>
                        <ul>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/profile/">Profil Singkat</a></li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/profile/history/">Sejarah</a>
                          </li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/profile/jobdesk/">Tugas dan Fungsi</a>
                          </li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/profile/visimisi/">Visi, Misi dan Motto</a>
                          </li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/profile/structure/">Struktur Organisasi</a>
                          </li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/profile/institution/">Aparatur</a>
                          </li>
                          <li class="menu-item">
                            <a target="_blank" href="<?php echo $this->baseUrl();?>/statistik/">Statistik P2KGK</a>
                          </li>
                        </ul>
                    </li><!-- .widget-pages end -->
                </ul><!-- .col-md-3.footer-widget-container end -->

                <ul class="col-md-3 col-sm-3 footer-widget-container">
                    <!-- .widget-pages start -->
                    <li class="widget widget_pages">
                        <div class="title">
                            <h3>Fasilitas</h3>
                        </div>

                        <ul>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/fasilitas/program/">Program Pelatihan</a>
                          </li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/fasilitas/sarana/">Sarana dan Prasarana</a>
                          </li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/fasilitas/mitra/">Kemitraan</a>
                          </li>
                          <li>
                            <a href="<?php echo $this->baseUrl();?>/fasilitas/aset/">Aset</a>
                          </li>
                        </ul>
                    </li><!-- .widget-pages end -->
                </ul><!-- .col-md-3.footer-widget-container end -->

                <ul class="col-md-3 col-sm-3 footer-widget-container">
                    <li class="widget widget-text">
                        <div class="title">
                            <h3>contact us</h3>
                        </div>

                        <address>
                          Jl Sawah Barat - Duren Sawit, Jakarta Timur, DKI Jakarta
                        </address>

                        <span class="text-big">
                          (021) 8611975
                        </span>
                        <br />

                        info : <a href="mailto:p2kgk.jaktim@gmail.com"> p2kgk.jaktim@gmail.com</a>
                        <br />
                        <ul class="footer-social-icons">
                            <li><a href="https://www.facebook.com/P2KGK-Jakarta-Timur-204466053220728/" class="fa fa-facebook" target="_blank"></a></li>
                            <li><a href="https://twitter.com/p2kgkjaktim" class="fa fa-twitter" target="_blank"></a></li>
                            <li><a href="https://plus.google.com/110983658397925793542" class="fa fa-google-plus" target="_blank"></a></li>
                        </ul><!-- .footer-social-icons end -->
                    </li><!-- .widget.widget-text end -->
                </ul><!-- .col-md-3.footer-widget-container end -->

                <ul class="col-md-3 col-sm-3 footer-widget-container ">
                  <!-- .widget.widget_text -->
                  <li class="widget widget_newsletterwidget">
                    <div class="title">
                      <h3>Chat dengan kami</h3>
                    </div>
                    <a href="ymsgr:sendIM?P2KGKJAKTIM" >
                      <img src="http://opi.yahoo.com/online?u=P2KGKJAKTIM &amp;m=g&amp;t=14" border="0" alt="P2KGK JAKTIM" />
                    </a>
                  </li><!-- .widget.widget_newsletterwidget end -->


                </ul><!-- .col-md-3.footer-widget-container end -->
            </div><!-- .row end -->
            <div class="row p2kgkfooter">
              <div class="col-md-12">
                <div class="row">
                  <div class="col-md-5 col-sm-12 pull-right">
                    <div class="col-md-12">
                      <div class="title">
                          <h3>Link Terkait</h3>
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                      <a href="#" target="_blank">
                        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/img/lsp.png" title="LSP">
                      </a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                      <a href="#" target="_blank">
                        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/img/p2kgk_.png" title="P2KGK">
                      </a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                      <a href="http://www.kemdikbud.go.id/" target="_blank">
                        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/img/dp.png" title="Dinas Pendidikan">
                      </a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                      <a href="http://bnsp.go.id/" target="_blank">
                        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/img/bnsp.png" title="BNSP">
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div><!-- .container end -->
    </footer><!-- #footer end -->

    <div class="copyright-container">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>Copyright © 2016 P2KGK Jakarta Timur. All Rights Reserved</p>
                </div><!-- .col-md-6 end -->

            </div><!-- .row end -->
        </div><!-- .container end -->
    </div><!-- .copyright-container end -->

    <a href="#" class="scroll-up">Scroll</a>
</div><!-- #footer-wrapper end -->

<script src="<?php echo $this->baseUrl();?>/js/bootstrap.min.js"></script><!-- .bootstrap script -->
<script src="<?php echo $this->baseUrl();?>/js/jquery.srcipts.min.js"></script><!-- modernizr, retina, stellar for parallax -->
<script src="<?php echo $this->baseUrl();?>/owl-carousel/owl.carousel.min.js"></script><!-- Carousels script -->
<script src="<?php echo $this->baseUrl();?>/masterslider/masterslider.min.js"></script><!-- Master slider main js -->
<script src="<?php echo $this->baseUrl();?>/js/jquery.matchHeight-min.js"></script><!-- for columns with background image -->
<script src="<?php echo $this->baseUrl();?>/js/jquery.magnific-popup.min.js"></script><!-- used for image lightbox -->
<script src="<?php echo $this->baseUrl();?>/js/portfolio.js"></script><!-- for portfolio -->
<script src="<?php echo $this->baseUrl();?>/js/jquery.dlmenu.min.js"></script><!-- for responsive menu -->

<script src="<?php echo $this->baseUrl();?>/js/include.js"></script><!-- custom js functions -->

<script>
    /* <![CDATA[ */
    jQuery(document).ready(function ($) {
        'use strict';

        function equalHeight() {
            $('.page-content.column-img-bkg *[class*="custom-col-padding"]').each(function () {
                var maxHeight = $(this).outerHeight();
                $('.page-content.column-img-bkg *[class*="img-bkg"]').height(maxHeight);
            });
        };

        $(document).ready(equalHeight);
        $(window).resize(equalHeight);

        // MASTER SLIDER START
        var slider = new MasterSlider();
        slider.setup('masterslider', {
            width: 1140, // slider standard width
            height: 854, // slider standard height
            space: 0,
            speed: 50,
            layout: "fullwidth",
            centerControls: false,
            loop: true,
            autoplay: true
                    // more slider options goes here...
                    // check slider options section in documentation for more options.
        });
        // adds Arrows navigation control to the slider.
        slider.control('arrows');

        // CLIENTS CAROUSEL START
        $('#client-carousel').owlCarousel({
            items: 6,
            loop: true,
            margin: 30,
            responsiveClass: true,
            mouseDrag: true,
            dots: false,
            responsive: {
                0: {
                    items: 2,
                    nav: true,
                    loop: true,
                    autoplay: true,
                    autoplayTimeout: 3000,
                    autoplayHoverPause: true,
                    responsiveClass: true
                },
                600: {
                    items: 3,
                    nav: true,
                    loop: true,
                    autoplay: true,
                    autoplayTimeout: 3000,
                    autoplayHoverPause: true,
                    responsiveClass: true
                },
                1000: {
                    items: 6,
                    nav: true,
                    loop: true,
                    autoplay: true,
                    autoplayTimeout: 3000,
                    autoplayHoverPause: true,
                    responsiveClass: true,
                    mouseDrag: true
                }
            }
        });

        // TESTIMONIAL CAROUSELS START
        $('#testimonial-carousel').owlCarousel({
            items: 1,
            loop: true,
            margin: 30,
            responsiveClass: true,
            mouseDrag: true,
            dots: false,
            autoheight: true,
            responsive: {
                0: {
                    items: 1,
                    nav: true,
                    loop: true,
                    autoplay: true,
                    autoplayTimeout: 3000,
                    autoplayHoverPause: true,
                    responsiveClass: true,
                    autoHeight: true
                },
                600: {
                    items: 1,
                    nav: true,
                    loop: true,
                    autoplay: true,
                    autoplayTimeout: 3000,
                    autoplayHoverPause: true,
                    responsiveClass: true,
                    autoHeight: true
                },
                1000: {
                    items: 1,
                    nav: true,
                    loop: true,
                    autoplay: true,
                    autoplayTimeout: 3000,
                    autoplayHoverPause: true,
                    responsiveClass: true,
                    mouseDrag: true,
                    autoHeight: true
                }
            }
        });
    });
    /* ]]> */
</script>
