<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN</title>
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/style.css" media="screen" title="no title" charset="utf-8">

    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <script src="<?php echo $this->baseUrl();?>/js/jquery.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/superfish.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/jquery.flexslider.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/hoverIntent.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/engine.js" charset="utf-8"></script>
  </head>
