<!DOCTYPE html>
<html>
    <head>
        <title>P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN</title>
        <meta name="description" content="Trucking is transportation and Logistics website template">
        <meta name="author" content="pixel-industry">
        <meta name="keywords" content="transportation, logistics, transportation template, logistics template, cargo, business">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Stylesheets -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/bootstrap.css"/><!-- bootstrap grid -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/masterslider/style/masterslider.css" /><!-- Master slider css -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/magnific-popup.css" /><!-- Lightbox styles -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/masterslider/skins/default/style.css" /><!-- Master slider default skin -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/animate.css"/><!-- animations -->
        <link rel='stylesheet' href='<?php echo $this->baseUrl();?>/owl-carousel/owl.carousel.css'/><!-- Client carousel -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/style.css"/><!-- template styles -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/color-aqua.css"/><!-- template main color -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/retina.css"/><!-- retina ready styles -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/responsive.css"/><!-- responsive styles -->

        <!-- Google Web fonts -->
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,800,700,600' rel='stylesheet' type='text/css'>

        <!-- Font icons -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/icon-fonts/font-awesome-4.3.0/css/font-awesome.min.css"/><!-- Fontawesome icons css -->

        <!-- Custom CSS -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/style-custom.css"/>

        <script src="<?php echo $this->baseUrl();?>/js/jquery-2.1.4.min.js"></script><!-- jQuery library -->

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script> <!-- google maps -->
        <script src="<?php echo $this->baseUrl();?>/js/jquery.ui.map.full.min.js"></script><!-- google maps -->
    </head>
