<!DOCTYPE html>
<html>
    <head>
        <title>P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN</title>
        <meta name="description" content="P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN">
        <meta name="author" content="P2KGK JAKTIM">
        <meta name="keywords" content="pelatihan guru, p2kgk jakarta timur, pusat pelatihan guru, jakarta timur, p2kgk, jakarta, guru, siswa, kejuruan, jakarta, dki jakarta, pelatihan jakarta, sertifikasi, p2kgkjaktim, P2KGK JAKTIM">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Favicon -->
        <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->baseUrl();?>/img/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->baseUrl();?>/img/favicon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->baseUrl();?>/img/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->baseUrl();?>/img/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->baseUrl();?>/img/favicon/favicon-16x16.png">
        <link rel="manifest" href="<?php echo $this->baseUrl();?>/img/favicon/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?php echo $this->baseUrl();?>/img/favicon/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">

        <!-- Stylesheets -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/bootstrap.css"/><!-- bootstrap grid -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/masterslider/style/masterslider.css" /><!-- Master slider css -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/magnific-popup.css" /><!-- Lightbox styles -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/masterslider/skins/default/style.css" /><!-- Master slider default skin -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/animate.css"/><!-- animations -->
        <link rel='stylesheet' href='<?php echo $this->baseUrl();?>/owl-carousel/owl.carousel.css'/><!-- Client carousel -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/style.css"/><!-- template styles -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/color-aqua.css"/><!-- template main color -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/retina.css"/><!-- retina ready styles -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/responsive.css"/><!-- responsive styles -->

        <!-- Google Web fonts -->
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,800,700,600' rel='stylesheet' type='text/css'>

        <!-- Font icons -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/icon-fonts/font-awesome-4.3.0/css/font-awesome.min.css"/><!-- Fontawesome icons css -->

        <!-- Custom CSS -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/style-custom.css"/>

        <script src="<?php echo $this->baseUrl();?>/js/jquery-2.1.4.min.js"></script><!-- jQuery library -->

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script> <!-- google maps -->
        <script src="<?php echo $this->baseUrl();?>/js/jquery.ui.map.full.min.js"></script><!-- google maps -->
    </head>
