<header>
  <div class="wrapper">
    <div id="logo">
      <a href="<?php echo $this->baseUrl();?>/index" title="">
        <img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="BPPTIK">
      </a>
    </div>
    <nav id="top-menu">
      <ul>
        <li class="menu-item">
          <a href="<?php echo $this->baseUrl();?>/faq/">FAQ</a>
        </li>
        <li class="menu-item">
          <a href="<?php echo $this->baseUrl();?>/contact/">Kontak</a>
        </li>
        <li class="menu-item ">
          <a href="<?php echo $this->baseUrl();?>/location/">Lokasi</a>
        </li>
        <li class="social-icons">
          <a href="mailto:bpptik@gmail.com" rel="nofollow">
            <img src="<?php echo $this->baseUrl();?>/images/social/email_small.png" width="16" height="16" alt="">
          </a>
          <a href="#" rel="nofollow">
            <img src="<?php echo $this->baseUrl();?>/images/social/facebook_small.png" width="16" height="16" alt="">
          </a>
          <a href="#" rel="nofollow">
            <img src="<?php echo $this->baseUrl();?>/images/social/twitter_small.png" width="16" height="16" alt="">
          </a>
          <a href="#" rel="nofollow">
            <img src="<?php echo $this->baseUrl();?>/images/social/youtube_small.png" width="16" height="16" alt="">
          </a>
          <a href="#" rel="nofollow">
            <img src="<?php echo $this->baseUrl();?>/images/social/feed_small.png" width="16" height="16" alt="">
          </a>
        </li>
      </ul>
    </nav>
    <div id="header-helpful">
      <div class="search-form">
        <form method="get" id="searchform" action="#">
          <fieldset>
            <input type="text" onblur="if (this.value == '') {this.value = 'Search';}" onfocus="if (this.value == 'Search') {this.value = '';}" value="Search" name="s" id="setop">
            <input type="submit" id="searchsubmit" value="Search">
          </fieldset>
        </form>
      </div>
      <span class="action">
        <span class="value">
        </span>
      </span>
    </div>
    <div class="cleaner">&nbsp;</div>
  </div>
</header>
