<nav id="nav-main-menu">
  <a class="btn_menu" id="toggle" href="#"></a>
  <div class="wrapper wrapper-menu">
    <ul id="menu-main" class="dropdown">
      <li class="menu-item">
        <a href="<?php echo $this->baseUrl();?>/index">Home</a>
      </li>
      <li class="menu-item menu-item-has-children">
        <a href="#" class="sf-with-ul">Profil<span class="sf-sub-indicator"> »</span>
        </a>
        <ul class="sub-menu">
          <li class="menu-item ">
            <a href="<?php echo $this->baseUrl();?>/profile/">Profil Singkat</a>
          </li>
          <li class="menu-item ">
            <a href="<?php echo $this->baseUrl();?>/profile/history/">Sejarah</a>
          </li>
          <li class="menu-item ">
            <a href="<?php echo $this->baseUrl();?>/profile/jobdesk/">Tugas dan Fungsi</a>
          </li>
          <li class="menu-item ">
            <a href="<?php echo $this->baseUrl();?>/profile/visimisi/">Visi, Misi dan Motto</a>
          </li>
          <li class="menu-item ">
            <a href="<?php echo $this->baseUrl();?>/profile/structure/">Struktur Organisasi</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/profile/institution/">Aparatur</a>
          </li>
        </ul>
      </li>
      <li class="menu-item menu-item-has-children">
        <a href="#" class="sf-with-ul">Layanan<span class="sf-sub-indicator"> »</span>
        </a>
        <ul class="sub-menu">
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/service/training/">Pelatihan</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/service/certification/">Uji Kompetensi dan Sertifikasi</a>
          </li>
          <!-- <li class="menu-item">
            <a href="#">Layanan Jasa TIK Lainnya</a>
          </li> -->
        </ul>
      </li>
      <li class="menu-item menu-item-has-children">
        <a href="#" class="sf-with-ul">Fasilitas<span class="sf-sub-indicator"> »</span></a>
        <ul class="sub-menu">
          <li class="menu-item ">
            <a href="<?php echo $this->baseUrl();?>/fasilitas/program/">Program Pelatihan</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/fasilitas/sarana/">Sarana dan Prasarana</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/fasilitas/mitra/">Kemitraan</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/fasilitas/aset/">Aset</a>
          </li>
        </ul>
      </li>
      <li  class="menu-item">
        <a href="<?php echo $this->baseUrl();?>/agenda/">Agenda</a>
      </li>
      <li class="menu-item">
        <a href="<?php echo $this->baseUrl();?>/news/">Berita</a>
      </li>
      <li class="menu-item">
        <a href="<?php echo $this->baseUrl();?>/article/">Artikel</a>
      </li>
      <li class="menu-item menu-item-has-children">
        <a href="#" class="sf-with-ul">Galeri<span class="sf-sub-indicator"> »</span>
        </a>
        <ul class="sub-menu">
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/gallery/photo/">Foto</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/gallery/video/">Video</a>
          </li>
        </ul>
      </li>
      <li class="menu-item menu-item-has-children">
        <a href="#" class="sf-with-ul">Download<span class="sf-sub-indicator"> »</span></a>
        <ul class="sub-menu">
          <li class="menu-item ">
            <a href="<?php echo $this->baseUrl();?>/report/training/">Laporan Pelatihan</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/report/certificate/">Laporan Sertifikat</a>
          </li>
          <li class="menu-item">
            <a href="<?php echo $this->baseUrl();?>/report/certification/">Laporan Sertifikasi</a>
          </li>
        </ul>
      </li>
      <li class="menu-item right-menu">
        <a href="<?php echo $this->baseUrl();?>/login/">Login</a>
      </li>
      <li class="cleaner">&nbsp;</li>
    </ul>
  </div>
</nav>
