<div class="header-inner">
<!-- .container start -->
<div class="container">
  <!-- .main-nav start -->
  <div class="main-nav">
      <!-- .row start -->
      <div class="row">
          <div class="col-md-12">
              <nav class="navbar navbar-default nav-left" role="navigation">
                  <!-- MAIN NAVIGATION -->
                  <div class="collapse navbar-collapse">
                      <ul class="nav navbar-nav">
                          <li class="dropdown">
                              <a href="<?php echo $this->baseUrl();?>/index">Home</a>
                          </li><!-- .dropdown end -->

                          <li class="dropdown">
                              <a href="#" data-toggle="dropdown" class="dropdown-toggle">Profil</a>
                              <ul class="dropdown-menu">
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/profile/">Profil Singkat</a></li>
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/profile/history/">Sejarah</a>
                                  </li>
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/profile/jobdesk/">Tugas dan Fungsi</a>
                                  </li>
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/profile/visimisi/">Visi, Misi dan Motto</a>
                                  </li>
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/profile/structure/">Struktur Organisasi</a>
                                  </li>
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/profile/institution/">Aparatur</a>
                                  </li>
                              </ul><!-- .dropdown-menu end -->
                          </li><!-- .dropdown end -->

                          <li class="dropdown">
                              <a href="" data-toggle="dropdown" class="dropdown-toggle">Layanan</a>
                              <ul class="dropdown-menu">
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/service/training/">Pelatihan</a>
                                  </li>
                                  <li>
                                    <a href="<?php echo $this->baseUrl();?>/service/certification/">Pelatihan dan Sertifikasi</a>
                                  </li>
                              </ul><!-- .dropdown-menu end -->
                          </li><!-- .dropdown end -->

                          <li class="dropdown">
                              <a href="" data-toggle="dropdown" class="dropdown-toggle">Fasilitas</a>
                              <ul class="dropdown-menu">
                                <li>
                                  <a href="<?php echo $this->baseUrl();?>/fasilitas/program/">Program Pelatihan</a>
                                </li>
                                <li>
                                  <a href="<?php echo $this->baseUrl();?>/fasilitas/sarana/">Sarana dan Prasarana</a>
                                </li>
                                <li>
                                  <a href="<?php echo $this->baseUrl();?>/fasilitas/mitra/">Kemitraan</a>
                                </li>
                                <li>
                                  <a href="<?php echo $this->baseUrl();?>/fasilitas/aset/">Aset</a>
                                </li>
                              </ul><!-- .dropdown-menu end -->
                          </li><!-- .dropdown end -->

                          <li><a href="<?php echo $this->baseUrl();?>/agenda/">Agenda</a></li>
                          <li><a href="<?php echo $this->baseUrl();?>/news/">News</a></li>
                          <li><a href="<?php echo $this->baseUrl();?>/article/">Artikel</a></li>

                          <li class="dropdown">
                              <a href="" data-toggle="dropdown" class="dropdown-toggle">Media</a>
                              <ul class="dropdown-menu">
                                  <li><a href="<?php echo $this->baseUrl();?>/gallery/photo/">Photo</a></li>
                                  <li><a href="<?php echo $this->baseUrl();?>/gallery/video/">Video</a></li>
                              </ul><!-- .dropdown-menu end -->
                          </li><!-- .dropdown end -->

                          <li class="dropdown">
                              <a href="" data-toggle="dropdown" class="dropdown-toggle">Download</a>
                              <ul class="dropdown-menu">
                                <li>
                                  <a href="<?php echo $this->baseUrl();?>/report/training/">Laporan Pelatihan</a>
                                </li>
                                <li>
                                  <a href="<?php echo $this->baseUrl();?>/report/certificate/">Laporan Sertifikat</a>
                                </li>
                                <li>
                                  <a href="<?php echo $this->baseUrl();?>/report/certification/">Laporan Sertifikasi</a>
                                </li>
                              </ul><!-- .dropdown-menu end -->
                          </li><!-- .dropdown end -->
                      </ul><!-- .nav.navbar-nav end -->

                      <?php include("../application/views/scripts/include/menu-responsive.phtml"); ?>


                      <a class="btn btn-medium" href="<?php echo $this->baseUrl();?>/login/">
                          <span>
                              Login
                          </span>
                      </a>
                  </div><!-- MAIN NAVIGATION END -->
              </nav><!-- .navbar.navbar-default end -->
          </div><!-- .col-md-12 end -->
      </div><!-- .row end -->
  </div><!-- .main-nav end -->
</div><!-- .container end -->
</div><!-- .header-inner end -->
