<div class="column column-narrow">
  <div class="widget-blue widget feature-posts">
    <p class="title">Pelatihan Terbaru</p>
    <ul class="posts posts-archive posts-side">
      <li>
        <div class="post-excerpt">
          <h2>
            <a href="#" title="Pelatihan Junior Network Administration dan Sertifikasi Junior Network Administrator" rel="bookmark">Pelatihan Junior Network Administration dan Sertifikasi Junior Network Administrator</a>
          </h2>
          <p class="post-meta">
            <span>
              <time datetime="2016-04-11" pubdate="">11th April 2016</time> </span>
          </p>
        </div>
          <div class="cleaner">&nbsp;</div>
        </li>
        <li>
          <div class="post-excerpt">
            <h2>
              <a href="#" title="Pelatihan Junior Technical Support dan Sertifikasi Junior Technical Support" rel="bookmark">Pelatihan Junior Technical Support dan Sertifikasi Junior Technical Support</a>
            </h2>
            <p class="post-meta">
              <span>
                <time datetime="2016-04-11" pubdate="">11th April 2016</time> </span>
            </p>
          </div>
            <div class="cleaner">&nbsp;</div>
          </li>
          <li>
            <div class="post-excerpt">
              <h2>
                <a href="#" title="Pelatihan Junior Web Programmer dan Sertifikasi Junior Web Programmer" rel="bookmark">Pelatihan Junior Web Programmer dan Sertifikasi Junior Web Programmer</a>
              </h2>
              <p class="post-meta">
                <span>
                  <time datetime="2016-04-11" pubdate="">11th April 2016</time> </span>
              </p>
            </div>
              <div class="cleaner">&nbsp;</div>
            </li>
        </ul>
        <div class="cleaner">&nbsp;</div>
      </div>
      <div class="cleaner">&nbsp;</div>
    </div>
