  <div class="widget-blue widget wpzoom-text">
    <p class="title">Link Terkait</p>
    <div class="textwidget">
      <a href="#" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/lsp.jpg" title="LSP">
      </a>
      <a href="#" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/p2kgk.jpg" title="P2KGK">
      </a>
      <a href="http://www.kemdikbud.go.id/" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/dp.jpg" title="Dinas Pendidikan">
      </a>
      <a href="http://bnsp.go.id/" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/bnsp-kcl.png" title="BNSP">
      </a>
    </div>
    <div class="cleaner">&nbsp;</div>
  </div>

  <div class="widget-blue widget wpzoom-text">
    <p class="title">Chat dengan kami</p>
    <div class="textwidget">
      <a href="ymsgr:sendIM?P2KGKJAKTIM" >
        <img src="http://opi.yahoo.com/online?u=P2KGKJAKTIM &amp;m=g&amp;t=14" border="0" alt="P2KGK JAKTIM" />
      </a>
    </div>
  </div>
