<aside class="col-md-3 aside aside-left">
  <div class="service-icon-center">
    <div class="icon-container">
        <img src="<?php echo $this->baseUrl();?>/images/profil.jpg" alt="" width="100" height="100"/>
    </div>
  </div>
    <ul class="aside-widgets">
        <li class="widget widget_nav_menu clearfix">
            <div class="title">
                <h3>My Account</h3>
            </div>
            <ul class="menu">
              <li>
                <a href="<?php echo $this->baseUrl();?>/user/3e72758f0fc77cdad787f58b41e9985f/edit/">Edit My Account</a>
              </li>
              <!-- <li>
                <a href="<?php echo $this->baseUrl();?>/user/3e72758f0fc77cdad787f58b41e9985f/training/">Daftar Pelatihan</a>
              </li> -->
              <li>
                <a href="<?php echo $this->baseUrl();?>/user/3e72758f0fc77cdad787f58b41e9985f/certification/">Daftar Pelatihan & Sertifikasi</a>
              </li>
              <li>
                <a href="<?php echo $this->baseUrl();?>/user/3e72758f0fc77cdad787f58b41e9985f/nilai/">Hasil Nilai</a>
              </li>
              <li>
                <a href="<?php echo $this->baseUrl();?>/user/3e72758f0fc77cdad787f58b41e9985f/history/">History</a>
              </li>
            </ul><!-- .menu end -->
        </li><!-- .widget.widget_nav_menu end -->

    </ul><!-- .aside-widgets end -->
</aside><!-- .aside.aside-left end -->
