<div class="column column-narrow">
  <div class="widget-blue widget feature-posts">
    <p class="title" style="text-align:center;">My Account</p>
    <div class="fotoprofil">
      <img src="<?php echo $this->baseUrl();?>/images/profil.jpg" alt="" width="100" height="100" style="margin:10px auto; display:block;"/>
    </div>
    <ul class="posts posts-archive posts-side">
      <li>
        <a href="<?php echo $this->baseUrl();?>/guru/edit/">Edit My Account</a>
        <div class="cleaner">&nbsp;</div>
      </li>
      <li>
        <a href="<?php echo $this->baseUrl();?>/guru/training/">Daftar Pelatihan</a>
        <div class="cleaner">&nbsp;</div>
      </li>
      <li>
        <a href="<?php echo $this->baseUrl();?>/guru/certification/">Daftar Pelatihan & Sertifikasi</a>
        <div class="cleaner">&nbsp;</div>
      </li>
      <li>
        <a href="<?php echo $this->baseUrl();?>/guru/nilai/">Hasil Nilai</a>
        <div class="cleaner">&nbsp;</div>
      </li>
      <li>
        <a href="<?php echo $this->baseUrl();?>/guru/history/">History</a>
        <div class="cleaner">&nbsp;</div>
      </li>
    </ul>
    <div class="cleaner">&nbsp;</div>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
