<div class="column column-narrow column-last">
  <div class="widget-blue widget wpzoom-text" id="wpzoom-text-widget-2">
    <p class="title">Link Terkait</p>
    <div class="textwidget">
      <a href="#" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/lsp.jpg" title="LSP">
      </a>
      <a href="#" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/p2kgk.jpg" title="P2KGK">
      </a>
      <a href="http://www.kemdikbud.go.id/" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/dp.jpg" title="Dinas Pendidikan">
      </a>
      <a href="http://bnsp.go.id/" target="_blank">
        <img class="aligncenter wp-image-152 " src="<?php echo $this->baseUrl();?>/images/bnsp-kcl.png" title="BNSP">
      </a>
    </div>
    <div class="cleaner">&nbsp;</div>
  </div>


  <div class="cleaner">&nbsp;</div>
</div>
