<div class="column column-narrow column-last">
  <div class="widget-blue widget wpzoom-text" id="wpzoom-text-widget-2">
    <p class="title">Link Terkait</p>
    <div class="textwidget">
      <a href="#" target="_blank">
        <img class="aligncenter wp-image-152 " src="http://202.89.117.94/wp-content/uploads/2014/11/koica2.png" title="KOICA">
      </a>
      <a href="http://www.lan.go.id/index.php" target="_blank">
        <img class="aligncenter wp-image-152 " src="http://202.89.117.94/wp-content/uploads/2014/10/lan-kecil.png" title="Lembaga Administrasi Negara">
      </a>
      <a href="http://kominfo.go.id/" target="_blank">
        <img class="aligncenter wp-image-152 " src="http://202.89.117.94/wp-content/uploads/2014/10/kominfo-kecil.png" title="Kominfo">
      </a>
      <a href="http://bnsp.go.id/" target="_blank">
        <img class="aligncenter wp-image-152 " src="http://202.89.117.94/wp-content/uploads/2014/11/bnsp-kcl.png" title="BNSP">
      </a>
    </div>
    <div class="cleaner">&nbsp;</div>
  </div>

  <div class="cleaner">&nbsp;</div>
</div>
