<div class="column column-narrow">
  <div class="widget-blue widget feature-posts">
    <p class="title">Konten Terbaru</p>
    <ul class="posts posts-archive posts-side">
      <li>
        <div class="post-cover">
          <a href="#" title="Sekretaris Badang Litbang SDM Kominfo Membuka Diklat CIO, ToT, dan Desain Grafis">
            <img src="images/KKP-210x100.jpg" alt="Sekretaris Badang Litbang SDM Kominfo Membuka Diklat CIO, ToT, dan Desain Grafis" class="Thumbnail thumbnail loop-main " width="210" height="100">
          </a>
        </div>
        <div class="post-excerpt">
          <h2>
            <a href="#" title="Permalink to Sekretaris Badang Litbang SDM Kominfo Membuka Diklat CIO, ToT, dan Desain Grafis" rel="bookmark">Sekretaris Badang Litbang SDM Kominfo Membuka Diklat CIO, ToT, dan Desain Grafis</a>
          </h2>
          <p class="post-meta">
            <span>
              <time datetime="2016-04-11" pubdate="">11th April 2016</time> </span>
          </p>
        </div>
          <div class="cleaner">&nbsp;</div>
        </li>
        <li>
          <div class="post-cover">
            <a href="#" title="Kembali Dibuka Kesempatan Diklat Teknis bidang TIK untuk PNS Pusat dan Daerah">
              <img src="images/20160302-diklat-tik-210x100.jpg" alt="Ilustrasi - Diklat Teknis bidang TIK di BPPTIK. (ist)" class="Thumbnail thumbnail loop-main " width="210" height="100">
            </a>
          </div>
          <div class="post-excerpt">
            <h2>
              <a href="#" title="Permalink to Kembali Dibuka Kesempatan Diklat Teknis bidang TIK untuk PNS Pusat dan Daerah" rel="bookmark">Kembali Dibuka Kesempatan Diklat Teknis bidang TIK untuk PNS Pusat dan Daerah</a>
            </h2>
            <p class="post-meta">
              <span>
                <time datetime="2016-03-02" pubdate="">2nd Maret 2016</time> </span>
            </p>
          </div>
            <div class="cleaner">&nbsp;</div>
          </li>
        </ul>
        <div class="cleaner">&nbsp;</div>
      </div>
      <div class="cleaner">&nbsp;</div>
    </div>
