<div class="column column-wide">
  <div class="widget">
    <!-- isi history -->
     <?php
    	//Zend_Debug::dump($this->data);die();
    	if ($this->data!=null) {
    		if($this->data[0]['gambar']!='') {
    			/* disini kalo mo ngasih style jak buat picturenya...src nya $this->baseUrl()/img/Profile/thisdatanya */
    			echo $this->data[0]['gambar'];
    		}
    		echo $this->data[0]['konten'];
    	} else {
    		echo 'konten kosong hubungi admin lah moso saya';
    	}
    ?>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
