<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i><b> ADD NEW AGENDA</b></center></div>
</br>
<script type="text/javascript">
    $(function () {
        $('#tgl').datetimepicker( {format: 'Y-MM-DD HH:mm'});
    });
</script>
<form class="form-horizontal" role="form" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
  <div class="form-group">
	    <label for="nama" class="col-sm-2 control-label">Judul Agenda</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama">
	    </div>
  </div>
  <div class="form-group">
	    <label for="tgl" class="col-sm-2 control-label">Tanggal dan Waktu</label>
	    <div class="col-sm-10">
        <div class='input-group date' id='tgl'>
            <input type='text' name="tgl" class="form-control" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
	    </div>
  </div>
  <div class="form-group">
    <label for="detail" class="col-sm-2 control-label">Detail Agenda</label>
     <div class="col-sm-10">
     	<textarea id="detail" name="detail"></textarea>
						<script type="text/javascript">
							CKEDITOR.replace( 'detail',  {
	allowedContent: true
} );
						</script>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/agenda/index'">Cancel</button>
    </div>
  </div>
</div>
</form>
</div>
</html>
