<div class="column column-wide">
  <div class="widget">
    <h1 class="post-title">Kontak</h1>
    <div class="divider">&nbsp;</div>
    <p>
      <strong>P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN</strong>
      <address class="">
        Jl Sawah Barat - Duren Sawit, Jakarta Timur, DKI Jakarta
      </address>
      <div class="kontaknya">
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/tlp.png" alt="telepon" />
          <span>Tlp : (021) 8611975, Hp : 081808953694</span>
        </div>
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/email.png" alt="telepon" />
          <span>E-mail : jaktimp2kgk@gmail.com, p2kgk.jaktim@gmail.com</span>
        </div>
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/fb.png" alt="facebook" />
          <span><a href="https://www.facebook.com/P2KGK-Jakarta-Timur-204466053220728/" title="facebook" target="_blank">Facebook</a></span>
        </div>
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/twitter.png" alt="twitter" />
          <span><a href="https://twitter.com/p2kgkjaktim" title="twitter" target="_blank">Twitter</a></span>
        </div>
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/gplus.png" alt="googleplus" />
          <span><a href="https://plus.google.com/110983658397925793542?prsrc=5" title="googleplus" target="_blank">Google +</a></span>
        </div>
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/ig.png" alt="instagram" />
          <span><a href="https://www.instagram.com/p2kgkjaktim/" title="instagram" target="_blank">Instagram</a></span>
        </div>
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/line.png" alt="Line" />
          <span>LINE : p2kgkJaktim</span>
        </div>
        <div class="kontak">
          <img src="<?php echo $this->baseUrl();?>/images/social/path.png" alt="Path" />
          <span>PATH: p2kgk Jakarta Timur</span>
        </div>
      </div>
    </p>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
