<div class="column column-wide">
  <div class="widget">
    <h1 class="post-title">Kontak</h1>
    <div class="divider">&nbsp;</div>
    <p>
      <strong>P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN</strong>
      <br> Jl Sawah Barat - Duren Sawit
      <br> Jakarta Timur - DKI Jakarta
      <br> Telp&nbsp;&nbsp; : +62 21 28645000
      <br> E-mail : bpptik at mail.kominfo.go.id
    </p>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
