<div class="column column-wide">
  <div class="widget">
    <h1 class="post-title">Kontak</h1>
    <div class="divider">&nbsp;</div>
    <p>
      <strong>P2KGK - PUSAT PENGEMBANGAN KOMPETENSI GURU DAN KEJURUAN</strong>
      <br> Jl Sawah Barat - Duren Sawit
      <br> Jakarta Timur - DKI Jakarta
      <br> Tlp : (021) 8611975, Hp : 081808953694
      <br> E-mail : jaktimp2kgk@gmail.com, p2kgk.jaktim@gmail.com
    </p>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
