<script type="text/javascript">
    $(function () {
        $('#tgl').datetimepicker();
    });
</script>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i> <b>ADD NEW PELATIHAN</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php
		}
	?>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
  <div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
      <div class="form-group">
    	    <label for="nama" class="col-sm-2 control-label">Nama Pelatihan</label>
    	    <div class="col-sm-10">
    	      <input type="text" class="form-control" id="nama" name="nama">
    	    </div>
      </div>
      <div class="form-group">
        <label for="tos" class="col-sm-2 control-label">Deskripsi</label>
         <div class="col-sm-10">
         	<textarea id="tos" name="tos"></textarea>
    						<script type="text/javascript">
    							CKEDITOR.replace( 'tos',  {
    	allowedContent: true
    } );
    						</script>
        </div>
      </div>
      <div class="form-group">
          <label for="tgl" class="col-sm-2 control-label">Tanggal dan Waktu</label>
          <div class="col-sm-10">
            <div class='input-group date' id='tgl'>
                <input type='text' name="tgl" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
          </div>
      </div>
      <div class="form-group">
  	    <label for="stat_peserta" class="col-sm-2 control-label">Status Peserta </label>
  	    <div class="col-sm-10">
          <select name="stat_peserta" id="stat_peserta" class="input-text form-control">
            <option value="">--Pilih Status Peserta--</option>
            <option value="1">Guru</option>
            <option value="2">Siswa</option>
            <option value="3">Keduanya</option>
          </select>
  	    </div>
    	</div>
      <div class="form-group">
  	    <label for="tingkat_peserta" class="col-sm-2 control-label">Tingkat Peserta</label>
  	    <div class="col-sm-10">
  				<select name="tingkat_peserta" class="input-text form-control" id="tingkat_peserta" >
            <option value="">--Pilih Tingkat Peserta--</option>
  					<option value="1">TK</option>
  					<option value="2">SD</option>
  					<option value="3">SMP</option>
  					<option value="4">SMA</option>
            <option value="5">SMK</option>
            <option value="6">Semuanya</option>
  				</select>
  	    </div>
    	</div>
      <div class="form-group">
  	    <label for="jenis_pelatihan" class="col-sm-2 control-label">Jenis Pelatihan  </label>
  	    <div class="col-sm-10">
          <select name="jenis_pelatihan" id="jenis_pelatihan" class="input-text form-control">
            <option value="">--Pilih Jenis Pelatihan--</option>
            <option value="1">Pelatihan</option>
            <option value="2">Pelatihan & Sertifikasi</option>
          </select>
  	    </div>
    	</div>
      <div class="form-group">
    	    <label for="gelombang" class="col-sm-2 control-label">Gelombang</label>
    	    <div class="col-sm-10">
    	      <input type="text" class="form-control" id="gelombang" name="gelombang">
    	    </div>
      </div>
      <div class="form-group">
    	    <label for="kuota" class="col-sm-2 control-label">Kuota Peserta</label>
    	    <div class="col-sm-10">
    	      <input type="text" class="form-control" id="kuota" name="kuota">
    	    </div>
      </div>
      <div class="form-group">
          <label for="kkm" class="col-sm-2 control-label">KKM (Boleh Kosong)</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="kkm" name="kkm">
          </div>
      </div>
      <div class="form-group">
  	    <label for="jenis_pelatihan" class="col-sm-2 control-label">Status Pendaftaran  </label>
  	    <div class="col-sm-10">
          BUKA/TUTUP
  	    </div>
    	</div>
      <div class="form-group">
  	    <label for="lembaga" class="col-sm-2 control-label">Lembaga Pelatihan  </label>
  	    <div class="col-sm-10">
          <select name="lembaga" id="lembaga" class="input-text form-control">
            <option value="">--Pilih Lembaga Pelatihan--</option>
            <?php
            $list = new Admin_Model_PelatihanModel();
            $lembaga = $list->getAllLembaga();
            foreach ($lembaga as $l ) {
            ?>
            <option value="<?php echo $l['ua_admin_id']?>"><?php echo $l['ua_firstname']." ".$l['ua_lastname']; ?></option>
            <?php } ?>
          </select>
  	    </div>
    	</div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Save</button>
           <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/pelatihan/index'">Cancel</button>
        </div>
      </div>
    </div>
  </form>
</div>
