<html>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"></script>
<script type="text/javascript">

	$(function() {
		$("table").tablesorter({debug: true})
		$("a.append").click(appendData);


	});

</script>
	<body>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
		<div class="panel panel-info">
		<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i>&nbsp;<b>LIST PELATIHAN</b>
			<div class="col-lg-6" style="float:right;position: relative;left: 30px;bottom: 6px;">
			</div>
		</div>
		<table class="table">
		        <thead>
		          <tr align="center">
		          	<th width="100">No</th>
		            <th>Nama Pelatihan</th>
                <th>Tgl Pelatihan</th>
                <th>Gelombang</th>
                <th>Peserta</th>
                <th>Tingkat Peserta</th>
		            <th>Status</th>
		            <th colspan="3">Action</th>
		          </tr>
		        </thead>
		        <tbody>
		         <?php for($a=0;$a < count($this->data);$a++){
		         	$b = $a+1;
		         		?>
		         <tr>
               <td><?php echo $b;?></td>
               <td><?php echo $this->data[$a]['nama_pelatihan'];?></td>
               <td><?php echo $this->data[$a]['tgl'];?></td>
               <td><?php echo $this->data[$a]['gelombang'];?></td>
		         	 <td><?php echo $this->data[$a]['status_peserta'];?></td>
		         	 <td><?php echo $this->data[$a]['tingkat_peserta'];?></td>
		         	 <td><?php echo $this->data[$a]['status_pendaftaran'];?></td>
		         	 <td width="50px">
								<a class="btn btn-default btn-lg active" href="<?php echo $this->baseUrl();?>/admin/pelatihan/edit/p/<?php echo $this->data[$a]['id_pelatihan']?>" style="cursor: pointer;">
									<span class="glyphicon glyphicon-edit">
										Edit</span>
								</a>
							</td>
							<td width="50px">
							 <a class="btn btn-default btn-lg active" href="<?php echo $this->baseUrl();?>/admin/pelatihan/peserta/p/<?php echo $this->data[$a]['id_pelatihan']?>" style="cursor: pointer;">
								 <span class="glyphicon glyphicon-search">
									 view</span>
							 </a>
						 </td>
		         	<td width="50px">
								<a class="btn btn-default btn-lg active" style="cursor: pointer;" onclick="hps('<?php echo $this->detail[$a]['id_pelatihan']?>')">
									<span class="glyphicon glyphicon-remove-circle">
										Delete</span>
									</a>
							</td>
		         </tr>
		         <?php }?>
		        </tbody>
		        <tfoot>
		        </tfoot>
		      </table>

		      </form>
		</div>

		<script>

		function hps(id){
			$.post('<?php echo $this->baseUrl()."/admin/pelatihan/delete/id"?>',{key: id}, function(data){
		          if(data.edit==true) {
					alert('Data Clear');
					parent.location.href = "<?php echo $this->baseUrl()?>/admin/pelatihan/index";
			      } else {
			    	  alert('Failed Clear Data');
			      }
		      });

		}
		</script>
	</body>
</html>
