<html>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"></script>
<script type="text/javascript">

	$(function() {
		$("table").tablesorter({debug: true})
		$("a.append").click(appendData);


	});

</script>
	<body>
	<?php
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php
		}
	?>
	<a class="btn btn-default btn-lg active" href="<?php echo $this->baseUrl();?>/admin/pelatihan/index" style="cursor: pointer;">
		<span class="glyphicon glyphicon-arrow-left">
			Back</span>
	</a>
	<a class="btn btn-default btn-lg active" href="<?php echo $this->baseUrl();?>/admin/pelatihan/excel" style="cursor: pointer;">
		<span class="glyphicon filetypes-xls">
			Export ke Excel</span>
	</a>
		<div class="panel panel-info">

		<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i>&nbsp;<b>LIST PESERTA PELATIHAN</b>
			<div class="col-lg-6" style="float:right;position: relative;left: 30px;bottom: 6px;">
			</div>
		</div>

		<table class="table">
		        <thead>
		          <tr align="center">
		          	<th width="100">No</th>
		            <th>ID Peserta (NIK/NIS)</th>
								<th>Nama Peserta</th>
		            <th>Status Peserta</th>
		            <th>Action</th>
		          </tr>
		        </thead>
		        <tbody>
		         <?php for($a=0;$a < count($this->data);$a++){
		         	$b = $a+1;
		         		?>
		         <tr>
               <td><?php echo $b;?></td>
							 <?php if($this->data[$a]['status_daftar']=='guru') {
								 $model = new User_Model_DbTables_GuruModel();
								 $guru = $model->getGurudet($this->data[$a]['id_peserta']);
								 $nama = $guru[0]['nama_lengkap'];
								 $nik = $guru[0]['nip'];
							 } else {
								 $model = new User_Model_DbTables_SiswaModel();
								 $siswa = $model->getSiswadet($this->data[$a]['id_peserta']);
								 $nama = $siswa[0]['nama_lengkap'];
								 $nik = $siswa[0]['nis'];
							 }
							 ?>
               <td><?php echo $nik;?></td>
							 <td><?php echo $nama;?></td>
               <td><?php echo strtoupper($this->data[$a]['status_daftar']);?></td>

		         	<td width="50px">
								<a class="btn btn-default btn-lg active" style="cursor: pointer;" onclick="hps('<?php echo $this->data[$a]['id_daftar']?>')">
									<span class="glyphicon glyphicon-remove-circle">
										Delete</span>
									</a>
							</td>
		         </tr>
		         <?php }?>
		        </tbody>
		        <tfoot>
		        </tfoot>
		      </table>

		      </form>
		</div>

		<script>

		function hps(id){
			$.post('<?php echo $this->baseUrl()."/admin/pelatihan/deletepeserta/id"?>',{key: id}, function(data){
		          if(data.edit==true) {
					alert('Data Clear');
					parent.location.href = "<?php echo $this->baseUrl()?>/admin/pelatihan/peserta/p/<?php echo $this->id?>";
			      } else {
			    	  alert('Failed Clear Data');
			      }
		      });

		}
		</script>
	</body>
</html>
