<div class="column column-wide">
  <div class="widget">
    <!-- isi service -->
    <h1 class="post-title">Gallery Foto</h1>
    <div class="divider">&nbsp;</div>
    <div class="gallery-content">
      <ul class="gallery">
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/1.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/2.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/11.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/4.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/5.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/8.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/12.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/14.jpg" alt="" /></li>
      </ul>
    </div>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
