<div class="page-title-style01 pt-bkg11">
  <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="breadcrumb-container">
            <ul class="breadcrumb">
              <li>You are here:</li>
              <li>
                <a href="<?php echo $this->baseUrl() ?>/index">Home</a>
              </li>
              <li>
                Gallery Photo
              </li>
            </ul><!-- .breadcrumb end -->
          </div><!-- .breadcrumb-container end -->
        </div>
      </div>
  </div>
</div>
<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="custom-heading02">
                    <h2>Gallery Photo</h2>
                    <p>
                        Kumpulan dokumentasi photo kegiatan P2KGK Jaktim
                    </p>
                </div><!-- .custom-heading02 end -->
            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->
    </div><!-- .container end -->
</div><!-- .page-content end -->
<div class="page-content">
    <div class="container">
        <div class="row">
            <ul class="vehicle-gallery clearfix p2kgkgallery">
                <li class="col-md-3">
                    <figure class="gallery-item-container">
                        <div class="gallery-item">
                            <img src="<?php echo $this->baseUrl();?>/images/kegiatan/1.jpg" alt="" />

                            <div class="hover-mask-container">
                                <div class="hover-mask"></div>
                                <div class="hover-zoom">
                                    <a href="<?php echo $this->baseUrl();?>/images/kegiatan/1.jpg" class="triggerZoom fa fa-search"></a>
                                </div><!-- .hover-details end -->
                            </div><!-- .hover-mask-container end -->
                        </div><!-- .service-item end -->

                        <figcaption>
                            <h3>MAN MEGA 13.6</h3>
                        </figcaption>
                    </figure><!-- .gallery-item-container end -->
                </li><!-- .gallery-item end -->
                <li class="col-md-3">
                    <figure class="gallery-item-container">
                        <div class="gallery-item">
                            <img src="<?php echo $this->baseUrl();?>/images/kegiatan/2.jpg" alt="" />

                            <div class="hover-mask-container">
                                <div class="hover-mask"></div>
                                <div class="hover-zoom">
                                    <a href="<?php echo $this->baseUrl();?>/images/kegiatan/2.jpg" class="triggerZoom fa fa-search"></a>
                                </div><!-- .hover-details end -->
                            </div><!-- .hover-mask-container end -->
                        </div><!-- .service-item end -->

                        <figcaption>
                            <h3>MAN MEGA 13.6</h3>
                        </figcaption>
                    </figure><!-- .gallery-item-container end -->
                </li><!-- .gallery-item end -->
                <li class="col-md-3">
                    <figure class="gallery-item-container">
                        <div class="gallery-item">
                            <img src="<?php echo $this->baseUrl();?>/images/kegiatan/8.jpg" alt="" />

                            <div class="hover-mask-container">
                                <div class="hover-mask"></div>
                                <div class="hover-zoom">
                                    <a href="<?php echo $this->baseUrl();?>/images/kegiatan/8.jpg" class="triggerZoom fa fa-search"></a>
                                </div><!-- .hover-details end -->
                            </div><!-- .hover-mask-container end -->
                        </div><!-- .service-item end -->

                        <figcaption>
                            <h3>MAN MEGA 13.6</h3>
                        </figcaption>
                    </figure><!-- .gallery-item-container end -->
                </li><!-- .gallery-item end -->
                <li class="col-md-3">
                    <figure class="gallery-item-container">
                        <div class="gallery-item">
                            <img src="<?php echo $this->baseUrl();?>/images/kegiatan/4.jpg" alt="" />

                            <div class="hover-mask-container">
                                <div class="hover-mask"></div>
                                <div class="hover-zoom">
                                    <a href="<?php echo $this->baseUrl();?>/images/kegiatan/4.jpg" class="triggerZoom fa fa-search"></a>
                                </div><!-- .hover-details end -->
                            </div><!-- .hover-mask-container end -->
                        </div><!-- .service-item end -->

                        <figcaption>
                            <h3>MAN MEGA 13.6</h3>
                        </figcaption>
                    </figure><!-- .gallery-item-container end -->
                </li><!-- .gallery-item end -->
                <li class="col-md-3">
                    <figure class="gallery-item-container">
                        <div class="gallery-item">
                            <img src="<?php echo $this->baseUrl();?>/images/kegiatan/5.jpg" alt="" />

                            <div class="hover-mask-container">
                                <div class="hover-mask"></div>
                                <div class="hover-zoom">
                                    <a href="<?php echo $this->baseUrl();?>/images/kegiatan/5.jpg" class="triggerZoom fa fa-search"></a>
                                </div><!-- .hover-details end -->
                            </div><!-- .hover-mask-container end -->
                        </div><!-- .service-item end -->

                        <figcaption>
                            <h3>MAN MEGA 13.6</h3>
                        </figcaption>
                    </figure><!-- .gallery-item-container end -->
                </li><!-- .gallery-item end -->
            </ul>
        </div>
    </div>
</div>

<!-- <div class="column column-wide">
  <div class="widget">
    <h1 class="post-title">Gallery Foto</h1>
    <div class="divider">&nbsp;</div>
    <div class="gallery-content">
      <ul class="gallery">
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/1.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/2.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/11.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/4.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/5.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/8.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/12.jpg" alt="" /></li>
        <li><img src="<?php echo $this->baseUrl();?>/images/kegiatan/14.jpg" alt="" /></li>
      </ul>
    </div>
  </div>
  <div class="cleaner">&nbsp;</div>
</div> -->
