<div class="column column-wide">
  <div class="widget">
    <!-- isi service -->
    <h1 class="post-title">Gallery Video</h1>
    <div class="divider">&nbsp;</div>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/HtdoyXLgb-Q" frameborder="0" allowfullscreen></iframe>

    <iframe width="420" height="315" src="https://www.youtube.com/embed/_qPf2P_CsdI" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="cleaner">&nbsp;</div>
</div>
